/**
 * One drawn diagram per technology, and the photograph beside it.
 *
 * The glossary could already say what a thing is in a sentence, and a sentence
 * is not enough. A telephone explained in words is a list of nouns; a telephone
 * drawn as a loop — voice, diaphragm, carbon, current, wire, magnet, diaphragm,
 * voice — is a thing you can follow with a finger and never forget. That is the
 * whole reason this file exists, and it is why every diagram here is a *path a
 * signal takes*, not a picture of an object sitting still.
 *
 * Drawn in code, for the same reasons `backdrops.tsx` and `icons.tsx` are: they
 * inherit the palette, they cost nothing to ship, and a schematic is repeating
 * structure — coils, poles, jacks, cores, dies — which is steadier written as a
 * loop than drawn by hand.
 *
 * **No words live in the SVG.** Every diagram places numbered pins, and the
 * words for those pins come from the glossary entry, which means they translate
 * with everything else. A diagram declares how many pins it draws and
 * `check:script` refuses a term whose step list is a different length, so a new
 * translation cannot silently leave a pin unlabelled.
 *
 * The photograph is separate and optional: `photos.ts` is generated by
 * `npm run fetch:photos` from Wikipedia, and a term with no usable photo simply
 * shows the diagram, which is the half that does the teaching anyway.
 */

import type { ReactNode } from 'react'
import type { Photo } from './photos'

// --- the shared frame --------------------------------------------------------

/**
 * Every diagram is drawn in this box and cropped by nothing, so a row of them
 * lines up and a reader learns where to look once.
 */
const W = 340
const H = 168

/** Flat tones, matching the backdrops: far structure, near structure, the one hot accent. */
const LINE = 'var(--fig-line)'
const FILL = 'var(--fig-fill)'
const EDGE = 'var(--fig-edge)'
const HOT = 'var(--fig-hot)'
const PIN = 'var(--fig-pin)'

const range = (n: number) => Array.from({ length: n }, (_, i) => i)

// --- primitives --------------------------------------------------------------

/** A labelled block: anything with an inside that the diagram does not open up. */
const Box = ({ x, y, w, h, r = 3 }: { x: number; y: number; w: number; h: number; r?: number }) => (
  <rect x={x} y={y} width={w} height={h} rx={r} fill={FILL} stroke={EDGE} strokeWidth="1.4" />
)

/** A conductor, or any path a signal travels. Dashed where the path is through air. */
const Wire = ({ d, hot, dash }: { d: string; hot?: boolean; dash?: boolean }) => (
  <path
    d={d}
    fill="none"
    stroke={hot ? HOT : LINE}
    strokeWidth={hot ? 1.8 : 1.4}
    strokeDasharray={dash ? '4 4' : undefined}
    strokeLinecap="round"
  />
)

/** An arrowhead on a wire, pointing the way the signal actually goes. */
const Tip = ({ x, y, a = 0, hot }: { x: number; y: number; a?: number; hot?: boolean }) => (
  <path
    d="M0 0 L-6 -3.4 L-6 3.4 Z"
    fill={hot ? HOT : LINE}
    transform={`translate(${x} ${y}) rotate(${a})`}
  />
)

/**
 * A numbered pin.
 *
 * The number is the one exception to the no-words rule, because a digit reads
 * the same in both languages and the alternative — leader lines to a caption —
 * needs twice the room and half as clear.
 */
const Pin = ({ n, x, y }: { n: number; x: number; y: number }) => (
  <g>
    <circle cx={x} cy={y} r="8.5" fill="var(--fig-pin-bg)" stroke={PIN} strokeWidth="1.3" />
    <text
      x={x}
      y={y + 3.6}
      textAnchor="middle"
      fontSize="10"
      fontWeight="700"
      fill={PIN}
      fontFamily="inherit"
    >
      {n}
    </text>
  </g>
)

/** A coil of wire seen from the side, `turns` humps long. */
const Coil = ({ x, y, turns, w = 7, h = 9 }: { x: number; y: number; turns: number; w?: number; h?: number }) => (
  <path
    d={`M${x} ${y} ` + range(turns).map(() => `q ${w / 2} ${-h} ${w} 0`).join(' ')}
    fill="none"
    stroke={LINE}
    strokeWidth="1.6"
  />
)

/** A person, from the side, small. Everything in Era 0 is a person. */
const Body = ({ x, y, s = 1 }: { x: number; y: number; s?: number }) => (
  <g transform={`translate(${x} ${y}) scale(${s})`} stroke={LINE} strokeWidth="1.5" fill="none">
    <circle cx="0" cy="-16" r="3.6" fill={LINE} stroke="none" />
    <path d="M0 -12 V-3" />
    <path d="M-4 -9 L4 -7 M0 -3 L-4 4 M0 -3 L4 4" />
  </g>
)

/** Ground, or the sea, or whatever is under the diagram. */
const Ground = ({ y = H - 18 }: { y?: number }) => (
  <path d={`M0 ${y} H${W}`} stroke={EDGE} strokeWidth="1.2" />
)

/** A hill, because half of Era 0 is about what a hill can see. */
const Hill = ({ x, w, h, base = H - 18 }: { x: number; w: number; h: number; base?: number }) => (
  <path d={`M${x} ${base} Q${x + w / 2} ${base - h} ${x + w} ${base} Z`} fill={FILL} stroke={EDGE} strokeWidth="1.2" />
)

/** A radiating wave: `n` arcs stepping outward from a point. */
const Waves = ({ x, y, n, from = 10, gap = 9, a = 55 }: { x: number; y: number; n: number; from?: number; gap?: number; a?: number }) => (
  <g fill="none" stroke={HOT} strokeWidth="1.3" opacity="0.85">
    {range(n).map((i) => {
      const r = from + i * gap
      const rad = (a * Math.PI) / 180
      return (
        <path
          key={i}
          d={`M${x + r * Math.cos(-rad)} ${y + r * Math.sin(-rad)} A${r} ${r} 0 0 1 ${x + r * Math.cos(rad)} ${y + r * Math.sin(rad)}`}
        />
      )
    })}
  </g>
)

/** A sine, `cycles` long, drawn as one path so it can be clipped or dashed. */
const sine = (x: number, y: number, len: number, cycles: number, amp: number) => {
  const step = len / (cycles * 2)
  let d = `M${x} ${y}`
  for (let i = 0; i < cycles * 2; i++) {
    d += ` q ${step / 2} ${i % 2 ? amp : -amp} ${step} 0`
  }
  return d
}

/** A battery cell: long plate, short plate. */
const Cell = ({ x, y }: { x: number; y: number }) => (
  <g stroke={LINE} strokeWidth="1.5">
    <path d={`M${x} ${y - 8} V${y + 8}`} />
    <path d={`M${x + 5} ${y - 4} V${y + 4}`} strokeWidth="3" />
  </g>
)

// --- the diagrams ------------------------------------------------------------

/**
 * A diagram and the number of pins it draws.
 *
 * `pins` is the contract with the glossary: a term whose `steps` list is not
 * exactly this long is a bug, and `check:script` says so by name.
 */
export interface Figure {
  pins: number
  draw: () => ReactNode
}

const FIGURES: Record<string, Figure> = {}
const figure = (id: string, pins: number, draw: () => ReactNode) => {
  FIGURES[id] = { pins, draw }
}

export const figureFor = (id: string): Figure | undefined => FIGURES[id]

// --- Era 0: people, distance, and line of sight -------------------------------

/** Two villages, one walker, four days. The pins are the days. */
figure('courier', 3, () => (
  <>
    <Ground />
    <Box x={12} y={104} w={54} h={40} />
    <path d="M18 104 L39 88 L60 104" fill="none" stroke={EDGE} strokeWidth="1.4" />
    <Box x={274} y={104} w={54} h={40} />
    <path d="M280 104 L301 88 L322 104" fill="none" stroke={EDGE} strokeWidth="1.4" />
    <Wire d="M74 144 H266" dash />
    <Body x={170} y={146} />
    {/* Out on top, back underneath: the shape of the 4 days a question costs. */}
    <Wire d="M104 62 H228" hot />
    <Tip x={230} y={62} hot />
    <Wire d="M236 84 H112" />
    <Tip x={110} y={84} a={180} />
    <Pin n={1} x={39} y={70} />
    <Pin n={2} x={170} y={110} />
    <Pin n={3} x={301} y={70} />
  </>
))

/** A post by a road: the message waits at the board instead of in a hand. */
figure('notice-board', 3, () => (
  <>
    <Ground />
    <Wire d={`M0 ${H - 18} H${W}`} />
    <g>
      <path d="M158 150 V96 M182 150 V96" stroke={EDGE} strokeWidth="2" />
      <Box x={132} y={54} w={76} h={46} />
      <rect x={140} y={62} width={24} height={14} fill={HOT} opacity="0.75" />
      <rect x={170} y={62} width={30} height={10} fill={EDGE} />
      <rect x={140} y={82} width={38} height={10} fill={EDGE} />
    </g>
    <Body x={82} y={150} />
    <Body x={258} y={150} />
    <Wire d="M96 130 H140" hot />
    <Tip x={142} y={130} hot />
    <Wire d="M200 130 H244" hot />
    <Tip x={246} y={130} hot />
    <Pin n={1} x={68} y={106} />
    <Pin n={2} x={170} y={34} />
    <Pin n={3} x={272} y={106} />
  </>
))

/** One bit, two hills, the speed of light. */
figure('signal-fire', 3, () => (
  <>
    <Ground />
    <Hill x={-10} w={140} h={78} />
    <Hill x={210} w={150} h={64} />
    <g transform="translate(60 68)">
      <path d="M0 4 q-9 -12 -3 -20 q3 6 6 3 q-2 -9 5 -14 q-2 12 6 16 q6 5 0 15 Z" fill={HOT} />
    </g>
    <Waves x={60} y={58} n={3} from={16} gap={10} a={70} />
    <Wire d="M76 56 L268 74" dash />
    <Tip x={270} y={74} a={5} />
    <Body x={286} y={90} s={0.85} />
    <Pin n={1} x={60} y={26} />
    <Pin n={2} x={172} y={44} />
    <Pin n={3} x={296} y={62} />
  </>
))

/** Arms in agreed positions, read through a telescope from the next tower. */
figure('semaphore', 4, () => {
  const tower = (x: number, a1: number, a2: number) => (
    <g>
      <path d={`M${x - 12} 150 L${x - 5} 84 H${x + 5} L${x + 12} 150 Z`} fill={FILL} stroke={EDGE} strokeWidth="1.3" />
      <path d={`M${x - 22} 78 H${x + 22}`} stroke={LINE} strokeWidth="2.4" />
      <path
        d={`M${x - 22} 78 L${x - 22 + 18 * Math.cos(a1)} ${78 + 18 * Math.sin(a1)}`}
        stroke={HOT}
        strokeWidth="3"
        strokeLinecap="round"
      />
      <path
        d={`M${x + 22} 78 L${x + 22 + 18 * Math.cos(a2)} ${78 + 18 * Math.sin(a2)}`}
        stroke={HOT}
        strokeWidth="3"
        strokeLinecap="round"
      />
    </g>
  )
  return (
    <>
      <Ground />
      {tower(52, -1.2, 0.9)}
      {tower(288, -1.2, 0.9)}
      <Wire d="M76 96 L262 96" dash />
      <Tip x={264} y={96} />
      <g stroke={EDGE} strokeWidth="1.4" fill="none">
        <path d="M244 108 L266 100" />
        <circle cx="242" cy="110" r="4" />
      </g>
      <Pin n={1} x={52} y={54} />
      <Pin n={2} x={170} y={80} />
      <Pin n={3} x={242} y={126} />
      <Pin n={4} x={288} y={54} />
    </>
  )
})

/** What the ground is allowed to block, and what the curve of the earth blocks anyway. */
figure('line-of-sight', 3, () => (
  <>
    <path d={`M0 160 Q170 118 340 160`} fill={FILL} stroke={EDGE} strokeWidth="1.3" />
    <Hill x={130} w={80} h={54} base={136} />
    <path d="M40 118 V78" stroke={EDGE} strokeWidth="2" />
    <path d="M300 126 V86" stroke={EDGE} strokeWidth="2" />
    <Wire d="M40 78 L300 86" dash />
    <Wire d="M40 78 L170 92" hot />
    <g stroke="var(--fig-no)" strokeWidth="2" strokeLinecap="round">
      <path d="M164 84 L180 100 M180 84 L164 100" />
    </g>
    <Pin n={1} x={40} y={58} />
    <Pin n={2} x={172} y={62} />
    <Pin n={3} x={300} y={66} />
  </>
))

// --- Era 1: AM radio ----------------------------------------------------------

/** The whole point of AM in one line: the loud wave carries the quiet one. */
figure('am-radio', 4, () => (
  <>
    <Wire d={sine(14, 42, 78, 2, 11)} hot />
    <Wire d={sine(110, 42, 92, 9, 7)} />
    <path
      d={`M222 42 ${range(26)
        .map((i) => {
          const t = i / 25
          const env = 9 + 8 * Math.sin(t * Math.PI * 2)
          return `L${222 + t * 104} ${42 + (i % 2 ? env : -env)}`
        })
        .join(' ')}`}
      fill="none"
      stroke={HOT}
      strokeWidth="1.5"
    />
    <path d={`M222 42 ${range(26).map((i) => { const t = i / 25; return `L${222 + t * 104} ${42 - (9 + 8 * Math.sin(t * Math.PI * 2))}` }).join(' ')}`} fill="none" stroke={LINE} strokeWidth="1" strokeDasharray="3 3" />
    <Box x={78} y={104} w={58} h={34} />
    <Coil x={90} y={128} turns={4} />
    <Box x={188} y={104} w={58} h={34} />
    <path d="M200 130 L216 112 L232 130" fill="none" stroke={LINE} strokeWidth="1.5" />
    <Wire d="M40 120 H74" />
    <Tip x={76} y={120} />
    <Wire d="M138 120 H184" hot />
    <Tip x={186} y={120} hot />
    <Wire d="M248 120 H292" hot />
    <Tip x={294} y={120} hot />
    <Body x={26} y={138} s={0.8} />
    <Pin n={1} x={26} y={96} />
    <Pin n={2} x={107} y={92} />
    <Pin n={3} x={217} y={92} />
    <Pin n={4} x={310} y={102} />
  </>
))

/** Oscillator, modulator, amplifier, antenna — in that order, always. */
figure('transmitter', 4, () => (
  <>
    <Ground />
    <Box x={14} y={62} w={56} h={40} />
    <Wire d={sine(22, 82, 40, 3, 7)} />
    <Box x={94} y={62} w={56} h={40} />
    <path d="M112 92 L122 72 L132 92" fill="none" stroke={LINE} strokeWidth="1.5" />
    <path d="M104 82 H140" stroke={LINE} strokeWidth="1.2" />
    <Box x={174} y={62} w={56} h={40} />
    <path d="M188 74 L216 82 L188 90 Z" fill="none" stroke={LINE} strokeWidth="1.5" />
    <Wire d="M70 82 H90" hot />
    <Tip x={92} y={82} hot />
    <Wire d="M150 82 H170" hot />
    <Tip x={172} y={82} hot />
    <Wire d="M230 82 H286" hot />
    <path d="M290 150 V26" stroke={LINE} strokeWidth="2.4" />
    <path d="M290 150 H262 M290 150 H318" stroke={EDGE} strokeWidth="1.2" />
    <Waves x={290} y={44} n={3} from={14} gap={9} a={70} />
    <Pin n={1} x={42} y={44} />
    <Pin n={2} x={122} y={44} />
    <Pin n={3} x={202} y={44} />
    <Pin n={4} x={290} y={14} />
  </>
))

/** A mast is a length, not a pole: the wave and the metal have to agree. */
figure('antenna', 4, () => (
  <>
    <Ground />
    <path d="M170 150 V30" stroke={LINE} strokeWidth="3" />
    <path d="M120 150 H220" stroke={EDGE} strokeWidth="1.4" />
    <g stroke={EDGE} strokeWidth="1.2">
      <path d="M170 46 L112 148 M170 46 L228 148" />
    </g>
    <Wire d="M170 150 L170 156 L120 156" hot />
    <Waves x={170} y={54} n={3} from={22} gap={11} a={62} />
    <g stroke={PIN} strokeWidth="1" strokeDasharray="3 3">
      <path d="M246 30 V150" />
      <path d="M240 30 H252 M240 150 H252" />
    </g>
    <Pin n={1} x={170} y={16} />
    <Pin n={2} x={246} y={90} />
    <Pin n={3} x={210} y={120} />
    <Pin n={4} x={104} y={156} />
  </>
))

/** Something spins, a coil crosses a field, current comes out. */
figure('generator', 4, () => (
  <>
    <g stroke={LINE} strokeWidth="1.6" fill="none">
      <circle cx="72" cy="86" r="34" />
      <path d="M72 52 L72 62 M72 110 L72 120 M38 86 L48 86 M96 86 L106 86" />
      <path d="M60 74 L84 98 M84 74 L60 98" />
    </g>
    <path d="M20 86 A52 52 0 0 1 38 60" fill="none" stroke={HOT} strokeWidth="1.6" />
    <Tip x={39} y={58} a={-50} hot />
    <Box x={140} y={62} w={54} h={48} />
    <path d="M148 70 H186 M148 102 H186" stroke={LINE} strokeWidth="3" />
    <Coil x={150} y={92} turns={4} />
    <Wire d="M106 86 H136" />
    <Wire d="M194 86 H236" hot />
    <Tip x={238} y={86} hot />
    <Box x={244} y={68} w={64} h={36} />
    <Wire d={sine(252, 86, 48, 3, 8)} hot />
    <Pin n={1} x={72} y={38} />
    <Pin n={2} x={167} y={42} />
    <Pin n={3} x={219} y={62} />
    <Pin n={4} x={276} y={122} />
  </>
))

/** Where the wave actually goes after it leaves the mast. */
figure('propagation', 4, () => (
  <>
    <path d={`M0 148 Q170 128 340 148 V168 H0 Z`} fill={FILL} stroke={EDGE} strokeWidth="1.2" />
    <path d="M0 34 H340" stroke={PIN} strokeWidth="1.4" strokeDasharray="6 5" opacity="0.8" />
    <path d="M40 140 V96" stroke={LINE} strokeWidth="2.4" />
    <Wire d="M42 100 L166 36" hot />
    <Wire d="M170 36 L292 122" hot />
    <Tip x={294} y={124} a={35} hot />
    <Wire d="M44 130 Q160 152 268 138" />
    <Tip x={270} y={138} a={-8} />
    <path d="M292 138 V112" stroke={LINE} strokeWidth="2" />
    <Pin n={1} x={40} y={80} />
    <Pin n={2} x={104} y={82} />
    <Pin n={3} x={170} y={20} />
    <Pin n={4} x={160} y={158} />
  </>
))

// --- Era 2: the telegraph -----------------------------------------------------

/** One circuit, two ends: a key that breaks it and a magnet that hears the break. */
figure('telegraph', 5, () => (
  <>
    <Cell x={30} y={86} />
    <Wire d="M35 78 V44 H92" />
    <g>
      <path d="M92 52 L138 40" stroke={LINE} strokeWidth="3" strokeLinecap="round" />
      <path d="M92 44 V60" stroke={EDGE} strokeWidth="2" />
      <circle cx="136" cy="52" r="2.6" fill={HOT} />
      <path d="M130 58 H146" stroke={EDGE} strokeWidth="2" />
    </g>
    <Wire d="M146 58 H206" hot />
    <Wire d="M206 58 V96" hot />
    <Coil x={192} y={104} turns={4} h={10} />
    <path d="M188 116 H236" stroke={LINE} strokeWidth="3" />
    <path d="M212 96 V116" stroke={EDGE} strokeWidth="3" />
    <path d="M244 92 L286 100" stroke={LINE} strokeWidth="3" strokeLinecap="round" />
    <path d="M244 84 V104" stroke={EDGE} strokeWidth="2" />
    <Waves x={288} y={104} n={2} from={12} gap={8} a={45} />
    <Wire d="M188 116 V140 H35 V94" />
    <Pin n={1} x={30} y={122} />
    <Pin n={2} x={114} y={24} />
    <Pin n={3} x={176} y={40} />
    <Pin n={4} x={212} y={140} />
    <Pin n={5} x={300} y={78} />
  </>
))

/** A lever, a spring, and one pair of contacts. Nothing else. */
figure('telegraph-key', 4, () => (
  <>
    <Box x={64} y={112} w={212} h={26} r={4} />
    <path d="M96 122 L262 96" stroke={LINE} strokeWidth="5" strokeLinecap="round" />
    <circle cx="270" cy="94" r="11" fill={FILL} stroke={EDGE} strokeWidth="1.6" />
    <path d="M96 122 V112" stroke={EDGE} strokeWidth="3" />
    <path d="M168 110 V122" stroke={HOT} strokeWidth="2.4" strokeDasharray="3 3" />
    <circle cx="168" cy="109" r="3" fill={HOT} />
    <circle cx="168" cy="122" r="3" fill={HOT} />
    <path d="M126 118 q4 -8 8 0 q4 8 8 0 q4 -8 8 0" fill="none" stroke={EDGE} strokeWidth="1.6" />
    <Wire d="M64 132 H30 V60" />
    <Wire d="M276 132 H310 V60" hot />
    <Pin n={1} x={276} y={72} />
    <Pin n={2} x={168} y={62} />
    <Pin n={3} x={134} y={90} />
    <Pin n={4} x={30} y={44} />
  </>
))

/** Short, long, and the silences — which are the part everybody forgets. */
figure('morse-code', 4, () => {
  // A single letter, drawn as the line actually behaves: high is current on.
  const marks = [1, 3, 1, 1] // dot dash dot dot, with a gap between each
  let x = 30
  const seg: ReactNode[] = []
  marks.forEach((len, i) => {
    const w = len * 14
    seg.push(<path key={`m${i}`} d={`M${x} 96 V64 H${x + w} V96`} fill="none" stroke={HOT} strokeWidth="2" />)
    x += w
    const gap = 14
    seg.push(<path key={`g${i}`} d={`M${x} 96 H${x + gap}`} stroke={LINE} strokeWidth="2" />)
    x += gap
  })
  return (
    <>
      <path d="M20 96 H320" stroke={EDGE} strokeWidth="1.2" />
      {seg}
      <path d="M30 112 H44" stroke={PIN} strokeWidth="1.4" />
      <path d="M30 108 V116 M44 108 V116" stroke={PIN} strokeWidth="1.4" />
      <path d="M58 112 H100" stroke={PIN} strokeWidth="1.4" />
      <path d="M58 108 V116 M100 108 V116" stroke={PIN} strokeWidth="1.4" />
      <path d={`M${x} 96 H310`} stroke={LINE} strokeWidth="2" strokeDasharray="4 4" />
      <Pin n={1} x={37} y={132} />
      <Pin n={2} x={79} y={132} />
      <Pin n={3} x={51} y={44} />
      <Pin n={4} x={280} y={76} />
    </>
  )
})

/** Current into a coil, iron pulled, the only way the 19th century moved anything at a distance. */
figure('electromagnet', 4, () => (
  <>
    <Cell x={28} y={100} />
    <Wire d="M33 92 V56 H88" hot />
    <Box x={88} y={70} w={92} h={26} r={2} />
    <Coil x={92} y={70} turns={10} w={9} h={12} />
    <g stroke={PIN} strokeWidth="1.1" fill="none" opacity="0.85">
      <path d="M134 66 C176 30 176 130 134 100" />
      <path d="M134 66 C92 30 92 130 134 100" />
    </g>
    <path d="M212 62 L212 108" stroke={LINE} strokeWidth="5" strokeLinecap="round" />
    <path d="M212 62 L268 56" stroke={LINE} strokeWidth="4" strokeLinecap="round" />
    <Wire d="M186 84 H206" hot />
    <Tip x={208} y={84} hot />
    <Wire d="M33 108 V140 H212 V116" />
    <Pin n={1} x={28} y={132} />
    <Pin n={2} x={134} y={124} />
    <Pin n={3} x={134} y={22} />
    <Pin n={4} x={252} y={34} />
  </>
))

/** A tired signal in, a fresh battery, a loud signal out. Repeat forever. */
figure('relay-station', 4, () => (
  <>
    <Wire d={sine(10, 60, 84, 4, 4)} />
    <Box x={110} y={40} w={120} h={80} />
    <Coil x={122} y={70} turns={5} h={9} />
    <path d="M120 82 H176" stroke={LINE} strokeWidth="2.6" />
    <path d="M156 60 L200 54" stroke={LINE} strokeWidth="3" strokeLinecap="round" />
    <circle cx="200" cy="54" r="2.6" fill={HOT} />
    <Cell x={196} y={96} />
    <Wire d="M201 88 V54" hot />
    <Wire d="M196 104 V112 H224" hot />
    <Wire d={sine(230, 60, 100, 4, 12)} hot />
    <Wire d="M94 60 H108" />
    <Tip x={110} y={60} />
    <Pin n={1} x={52} y={38} />
    <Pin n={2} x={140} y={134} />
    <Pin n={3} x={196} y={132} />
    <Pin n={4} x={280} y={34} />
  </>
))

// --- Era 3: the telephone -----------------------------------------------------

/**
 * The loop that took a telecommunications graduate a picture to understand:
 * sound is pressure, pressure is resistance, resistance is current, current is
 * a magnet, a magnet is a moving sheet, and a moving sheet is sound again.
 */
figure('telephone', 6, () => (
  <>
    <Body x={20} y={92} s={0.75} />
    <Waves x={30} y={80} n={2} from={9} gap={7} a={40} />
    <g>
      <path d="M56 62 V98" stroke={LINE} strokeWidth="2.4" />
      <path d="M56 62 q14 18 0 36" fill="none" stroke={HOT} strokeWidth="2" />
      <Box x={64} y={66} w={26} h={28} r={2} />
      {range(9).map((i) => (
        <circle key={i} cx={70 + (i % 3) * 8} cy={72 + Math.floor(i / 3) * 8} r="2.2" fill={LINE} />
      ))}
    </g>
    <Cell x={104} y={124} />
    <Wire d="M90 80 H140 V116" hot />
    <Wire d="M109 132 H140" />
    <Wire d="M140 80 H208" hot />
    <path d="M168 80 h0" />
    <g>
      <Box x={208} y={66} w={30} h={28} r={2} />
      <Coil x={212} y={90} turns={3} h={10} />
      <path d="M244 62 V98" stroke={LINE} strokeWidth="2.4" />
      <path d="M244 62 q-14 18 0 36" fill="none" stroke={HOT} strokeWidth="2" />
    </g>
    <Waves x={252} y={80} n={2} from={9} gap={7} a={40} />
    <Body x={290} y={92} s={0.75} />
    <Pin n={1} x={22} y={56} />
    <Pin n={2} x={77} y={38} />
    <Pin n={3} x={104} y={152} />
    <Pin n={4} x={174} y={56} />
    <Pin n={5} x={223} y={38} />
    <Pin n={6} x={292} y={56} />
  </>
))

/** A human router: every line lands here, and a person joins two of them by hand. */
figure('switchboard', 4, () => (
  <>
    <Box x={44} y={26} w={252} h={72} />
    {range(24).map((i) => (
      <circle
        key={i}
        cx={60 + (i % 12) * 20}
        cy={44 + Math.floor(i / 12) * 26}
        r="5"
        fill="none"
        stroke={EDGE}
        strokeWidth="1.4"
      />
    ))}
    <circle cx="80" cy="44" r="5" fill={HOT} />
    <circle cx="260" cy="70" r="5" fill={HOT} />
    <path d="M80 44 Q140 130 260 70" fill="none" stroke={HOT} strokeWidth="2" />
    <Body x={170} y={150} s={0.9} />
    <path d="M162 134 q8 -8 16 0" fill="none" stroke={LINE} strokeWidth="1.4" />
    <Pin n={1} x={80} y={16} />
    <Pin n={2} x={170} y={112} />
    <Pin n={3} x={260} y={16} />
    <Pin n={4} x={202} y={148} />
  </>
))

/** Why a building in the middle beats wires between everybody. */
figure('exchange', 3, () => {
  const ring = range(6).map((i) => {
    const a = (i / 6) * Math.PI * 2 - Math.PI / 2
    return [252 + 62 * Math.cos(a), 84 + 52 * Math.sin(a)] as const
  })
  const mesh = range(5).map((i) => {
    const a = (i / 5) * Math.PI * 2 - Math.PI / 2
    return [76 + 50 * Math.cos(a), 84 + 46 * Math.sin(a)] as const
  })
  return (
    <>
      <g stroke={LINE} strokeWidth="1" opacity="0.75">
        {mesh.map(([x1, y1], i) => mesh.slice(i + 1).map(([x2, y2], j) => <path key={`${i}-${j}`} d={`M${x1} ${y1} L${x2} ${y2}`} />))}
      </g>
      {mesh.map(([x, y], i) => (
        <circle key={i} cx={x} cy={y} r="5" fill={FILL} stroke={EDGE} strokeWidth="1.4" />
      ))}
      <path d="M162 84 H186" stroke={EDGE} strokeWidth="1.4" strokeDasharray="4 3" />
      <g stroke={HOT} strokeWidth="1.3">
        {ring.map(([x, y], i) => (
          <path key={i} d={`M${x} ${y} L252 84`} />
        ))}
      </g>
      {ring.map(([x, y], i) => (
        <circle key={i} cx={x} cy={y} r="5" fill={FILL} stroke={EDGE} strokeWidth="1.4" />
      ))}
      <rect x={240} y={72} width={24} height={24} rx="3" fill={FILL} stroke={HOT} strokeWidth="1.6" />
      <Pin n={1} x={76} y={148} />
      <Pin n={2} x={252} y={148} />
      <Pin n={3} x={252} y={20} />
    </>
  )
})

/** The dial counts, the switch steps, and the operator is out of a job. */
figure('strowger', 4, () => (
  <>
    <g>
      <circle cx="66" cy="86" r="36" fill={FILL} stroke={EDGE} strokeWidth="1.6" />
      <circle cx="66" cy="86" r="13" fill="none" stroke={EDGE} strokeWidth="1.2" />
      {range(10).map((i) => {
        const a = (i / 10) * Math.PI * 2 - Math.PI / 2
        return <circle key={i} cx={66 + 25 * Math.cos(a)} cy={86 + 25 * Math.sin(a)} r="3.4" fill={EDGE} />
      })}
      <path d="M66 86 L92 66" stroke={HOT} strokeWidth="2" />
    </g>
    <g>
      {range(3).map((i) => (
        <path key={i} d={`M${132 + i * 26} 118 V72 H${144 + i * 26} V118`} fill="none" stroke={HOT} strokeWidth="1.8" />
      ))}
      <path d="M120 118 H216" stroke={LINE} strokeWidth="1.4" />
    </g>
    <Wire d="M104 86 H124" />
    <Tip x={126} y={86} />
    <g>
      <path d="M262 40 V132" stroke={EDGE} strokeWidth="2" />
      {range(6).map((i) => (
        <circle key={i} cx="262" cy={46 + i * 17} r="4" fill="none" stroke={EDGE} strokeWidth="1.3" />
      ))}
      <circle cx="262" cy="97" r="4" fill={HOT} />
      <path d="M232 128 L258 99" stroke={HOT} strokeWidth="2" />
      <path d="M226 128 h12" stroke={LINE} strokeWidth="3" />
    </g>
    <Wire d="M216 118 H224" />
    <Pin n={1} x={66} y={38} />
    <Pin n={2} x={158} y={44} />
    <Pin n={3} x={232} y={150} />
    <Pin n={4} x={296} y={68} />
  </>
))

/** One plug, one voltage, one meaning — decided once, obeyed by everybody. */
figure('standard', 3, () => (
  <>
    <Box x={16} y={62} w={72} h={44} />
    <path d="M88 74 h26 v8 h-26 M88 90 h26 v8 h-26" fill="none" stroke={HOT} strokeWidth="1.6" />
    <Box x={132} y={54} w={76} h={60} />
    <path d="M132 74 h-18 M132 90 h-18" stroke={HOT} strokeWidth="1.6" />
    <path d="M208 74 h18 M208 90 h18" stroke={HOT} strokeWidth="1.6" />
    <path d="M148 70 H192 M148 84 H192 M148 98 H176" stroke={EDGE} strokeWidth="1.6" />
    <Box x={252} y={62} w={72} h={44} />
    <path d="M252 74 h-26 v8 h26 M252 90 h-26 v8 h26" fill="none" stroke={HOT} strokeWidth="1.6" />
    <Pin n={1} x={52} y={40} />
    <Pin n={2} x={170} y={32} />
    <Pin n={3} x={288} y={40} />
  </>
))

// --- Era 4: electronics -------------------------------------------------------

/** A hot wire boils off electrons, a mesh decides how many get across. */
figure('vacuum-tube', 5, () => (
  <>
    <path d="M118 132 h104 v-64 a52 44 0 0 0 -104 0 Z" fill={FILL} stroke={LINE} strokeWidth="1.8" />
    <path d="M148 118 q8 -14 0 -28 q-8 -14 0 -22" fill="none" stroke={HOT} strokeWidth="2" />
    <path d="M138 116 H176" stroke={LINE} strokeWidth="3" />
    <path d="M132 88 H208" stroke={LINE} strokeWidth="1.4" strokeDasharray="5 5" />
    <path d="M128 58 H212" stroke={LINE} strokeWidth="3" />
    <g fill={HOT}>
      {range(5).map((i) => (
        <circle key={i} cx={142 + i * 14} cy={74 + (i % 2) * 6} r="2.4" />
      ))}
    </g>
    <Wire d="M118 132 V150 H60" />
    <Wire d="M170 88 H70" />
    <Wire d="M170 58 V32 H262" hot />
    <Pin n={1} x={148} y={144} />
    <Pin n={2} x={104} y={116} />
    <Pin n={3} x={58} y={88} />
    <Pin n={4} x={186} y={74} />
    <Pin n={5} x={286} y={32} />
  </>
))

/** No glass, no vacuum, no electronics. The most boring bottleneck in the game. */
figure('glassblowing', 4, () => (
  <>
    <Ground />
    <g>
      <path d="M22 96 q-12 -14 0 -28 q12 14 0 28" fill={HOT} opacity="0.8" />
      <path d="M14 120 q10 -12 16 0 Z" fill={HOT} opacity="0.4" />
    </g>
    <path d="M56 82 H128" stroke={LINE} strokeWidth="4" />
    <path d="M128 82 q26 -26 44 0 q-18 26 -44 0" fill={FILL} stroke={LINE} strokeWidth="1.8" />
    <Body x={80} y={150} s={0.85} />
    <Box x={214} y={64} w={54} h={40} />
    <circle cx="241" cy="84" r="11" fill="none" stroke={LINE} strokeWidth="1.5" />
    <path d="M241 84 L249 77" stroke={HOT} strokeWidth="1.8" />
    <Wire d="M180 84 H210" hot />
    <Tip x={212} y={84} hot />
    <Wire d="M268 84 H302" />
    <path d="M302 74 v20" stroke={LINE} strokeWidth="2" />
    <Pin n={1} x={22} y={54} />
    <Pin n={2} x={150} y={44} />
    <Pin n={3} x={241} y={126} />
    <Pin n={4} x={306} y={54} />
  </>
))

/** Lead, acid, and the fact that nothing electrical starts without a cell. */
figure('sulphuric-acid', 4, () => (
  <>
    <path d="M76 40 V138 H264 V40" fill="none" stroke={LINE} strokeWidth="2" />
    <path d="M76 62 H264 V138 H76 Z" fill={FILL} opacity="0.55" />
    <path d="M76 62 q24 8 47 0 q24 -8 47 0 q24 8 47 0 q24 -8 47 0" fill="none" stroke={HOT} strokeWidth="1.4" />
    <rect x={114} y={30} width={16} height={94} fill={FILL} stroke={LINE} strokeWidth="1.6" />
    <rect x={210} y={30} width={16} height={94} fill={FILL} stroke={LINE} strokeWidth="1.6" />
    <path d="M122 30 V16 H100" stroke={LINE} strokeWidth="1.6" fill="none" />
    <path d="M218 30 V16 H240" stroke={HOT} strokeWidth="1.8" fill="none" />
    <g fill={HOT} opacity="0.8">
      {range(6).map((i) => (
        <circle key={i} cx={146 + i * 14} cy={80 + (i % 3) * 18} r="2.4" />
      ))}
    </g>
    <Pin n={1} x={122} y={150} />
    <Pin n={2} x={218} y={150} />
    <Pin n={3} x={170} y={52} />
    <Pin n={4} x={252} y={16} />
  </>
))

/** Feed the output back into the input and the thing sings on its own. */
figure('oscillator', 4, () => (
  <>
    <Box x={110} y={60} w={80} h={48} />
    <path d="M126 70 L166 84 L126 98 Z" fill="none" stroke={LINE} strokeWidth="1.6" />
    <Wire d="M40 84 H106" />
    <Tip x={108} y={84} />
    <Wire d="M190 84 H244" hot />
    <Tip x={246} y={84} hot />
    <Wire d="M214 84 V136 H150" hot />
    <Tip x={148} y={136} a={180} hot />
    <Wire d="M150 136 H84 V90" hot />
    <g>
      <Coil x={52} y={54} turns={3} h={8} />
      <path d="M46 66 H70 M50 72 H66" stroke={LINE} strokeWidth="2" />
    </g>
    <Wire d={sine(252, 84, 74, 3, 12)} hot />
    <Pin n={1} x={58} y={36} />
    <Pin n={2} x={150} y={40} />
    <Pin n={3} x={116} y={152} />
    <Pin n={4} x={300} y={52} />
  </>
))

/** A weak thing steering a strong thing. Every repeater after this is the same trick. */
figure('amplifier', 4, () => (
  <>
    <Wire d={sine(14, 90, 66, 3, 5)} />
    <path d="M110 46 L110 134 L196 90 Z" fill={FILL} stroke={LINE} strokeWidth="1.8" />
    <Wire d="M80 90 H108" />
    <Wire d="M196 90 H226" hot />
    <Tip x={228} y={90} hot />
    <Wire d={sine(232, 90, 96, 3, 22)} hot />
    <Cell x={148} y={28} />
    <Wire d="M153 36 V52" />
    <Pin n={1} x={46} y={62} />
    <Pin n={2} x={148} y={12} />
    <Pin n={3} x={140} y={90} />
    <Pin n={4} x={280} y={140} />
  </>
))

// --- Era 5: the first machine -------------------------------------------------

/**
 * The 3 gates, one per row, all of them the same 2 switches moved around.
 *
 * Drawn as switches rather than as the schoolbook gate symbols on purpose: the
 * symbols are a later shorthand, and the point of this era is that somebody
 * looked at a telegraph relay — a switch another switch throws — and saw
 * arithmetic. Only the rows that conduct are drawn hot.
 */
const dot = (x: number, y: number) => <circle cx={x} cy={y} r="2.8" fill={EDGE} />

/** A knife switch: the blade lies almost flat when it is closed, up when it is not. */
const Blade = ({ x, y, open, hot }: { x: number; y: number; open?: boolean; hot?: boolean }) => (
  <>
    <Wire d={open ? `M${x} ${y} L${x + 21} ${y - 15}` : `M${x} ${y} L${x + 26} ${y - 4}`} hot={hot} />
    {dot(x, y)}
    {dot(x + 28, y)}
  </>
)

/** The answer, at the end of every row: on, or off. */
const Lamp = ({ x, y, lit }: { x: number; y: number; lit?: boolean }) =>
  lit ? (
    <g>
      <circle cx={x} cy={y} r="16" fill={HOT} opacity="0.18" />
      <circle cx={x} cy={y} r="10" fill={HOT} stroke={EDGE} strokeWidth="1.4" />
    </g>
  ) : (
    <g>
      <circle cx={x} cy={y} r="10" fill={FILL} stroke={EDGE} strokeWidth="1.4" />
      <path d={`M${x - 4.5} ${y - 4.5} L${x + 4.5} ${y + 4.5} M${x + 4.5} ${y - 4.5} L${x - 4.5} ${y + 4.5}`} stroke={EDGE} strokeWidth="1.2" fill="none" />
    </g>
  )

figure('logic-gate', 4, () => (
  <>
    {/* AND: 2 blades in a line. Both closed, so the lamp lights. */}
    <Wire d="M16 34 H56" hot />
    <Blade x={56} y={34} hot />
    <Wire d="M84 34 H112" hot />
    <Blade x={112} y={34} hot />
    <Wire d="M140 34 H232" hot />
    <Lamp x={250} y={34} lit />
    {/* OR: the same 2 blades side by side. One is open and it lights anyway. */}
    <Wire d="M16 86 H44" hot />
    <Wire d="M44 86 V68 H56" />
    <Blade x={56} y={68} open />
    <Wire d="M84 68 H132 V86" />
    <Wire d="M44 86 V104 H56" hot />
    <Blade x={56} y={104} hot />
    <Wire d="M84 104 H132 V86" hot />
    <Wire d="M132 86 H232" hot />
    <Lamp x={250} y={86} lit />
    {/* NOT: the current itself holds the blade open, so being fed puts it out. */}
    <Wire d="M16 136 H56" hot />
    <Blade x={56} y={136} open />
    <Wire d="M84 136 H232" dash />
    <Lamp x={250} y={136} />
    <Pin n={1} x={190} y={16} />
    <Pin n={2} x={190} y={64} />
    <Pin n={3} x={190} y={118} />
    <Pin n={4} x={296} y={86} />
  </>
))

// --- Era 6: computing ---------------------------------------------------------

/** A ring per bit, magnetised one way or the other, and it remembers with the power off. */
figure('core-memory', 4, () => (
  <>
    <g stroke={EDGE} strokeWidth="1.2">
      {range(4).map((i) => (
        <path key={`h${i}`} d={`M46 ${52 + i * 26} H294`} />
      ))}
      {range(6).map((i) => (
        <path key={`v${i}`} d={`M${76 + i * 38} 34 V142`} />
      ))}
    </g>
    {range(4).map((r) =>
      range(6).map((c) => {
        const on = (r + c) % 3 === 0
        return (
          <circle
            key={`${r}-${c}`}
            cx={76 + c * 38}
            cy={52 + r * 26}
            r="7.5"
            fill="none"
            stroke={on ? HOT : LINE}
            strokeWidth="2.4"
            transform={`rotate(${on ? 30 : -30} ${76 + c * 38} ${52 + r * 26})`}
          />
        )
      }),
    )}
    <Wire d="M20 52 H44" hot />
    <Wire d="M76 20 V32" hot />
    <Pin n={1} x={152} y={20} />
    <Pin n={2} x={22} y={78} />
    <Pin n={3} x={76} y={158} />
    <Pin n={4} x={296} y={158} />
  </>
))

/** A hole is a 1 and card stock is a 0, and you can hold the program in your hand. */
figure('punched-card', 4, () => (
  <>
    <path d="M52 36 H286 V132 H52 V50 L66 36" fill={FILL} stroke={LINE} strokeWidth="1.6" />
    {range(3).map((r) =>
      range(9).map((c) => {
        const hole = (r * 9 + c) % 4 === 1
        return hole ? (
          <rect key={`${r}-${c}`} x={74 + c * 22} y={58 + r * 24} width={11} height={13} rx="1.5" fill="var(--fig-pin-bg)" stroke={HOT} strokeWidth="1.2" />
        ) : (
          <rect key={`${r}-${c}`} x={74 + c * 22} y={58 + r * 24} width={11} height={13} rx="1.5" fill="none" stroke={EDGE} strokeWidth="1" />
        )
      }),
    )}
    <g stroke={LINE} strokeWidth="1.6">
      {range(9).map((i) => (
        <path key={i} d={`M${79 + i * 22} 22 V34`} />
      ))}
    </g>
    <Wire d="M286 84 H320" hot />
    <Pin n={1} x={40} y={44} />
    <Pin n={2} x={90} y={152} />
    <Pin n={3} x={180} y={16} />
    <Pin n={4} x={316} y={62} />
  </>
))

/** Two voltages, and everything that has ever been sent down a wire since. */
figure('binary', 4, () => {
  const bits = [1, 0, 0, 1, 0, 0, 0, 1]
  let d = 'M28 110'
  bits.forEach((b, i) => {
    const x = 28 + i * 30
    d += ` L${x} ${b ? 62 : 110} L${x + 30} ${b ? 62 : 110}`
  })
  return (
    <>
      <path d="M28 62 H292" stroke={EDGE} strokeWidth="1" strokeDasharray="4 4" />
      <path d="M28 110 H292" stroke={EDGE} strokeWidth="1" strokeDasharray="4 4" />
      <path d={d} fill="none" stroke={HOT} strokeWidth="2" />
      <g fill={PIN} fontSize="11" fontWeight="700" fontFamily="inherit" textAnchor="middle">
        {bits.map((b, i) => (
          <text key={i} x={43 + i * 30} y="138">
            {b}
          </text>
        ))}
      </g>
      <Pin n={1} x={14} y={62} />
      <Pin n={2} x={14} y={110} />
      <Pin n={3} x={160} y={38} />
      <Pin n={4} x={306} y={134} />
    </>
  )
})

/** A node does not know the route. It knows one line of a table, and that is enough. */
figure('routing-table', 4, () => (
  <>
    <circle cx="66" cy="86" r="18" fill={FILL} stroke={HOT} strokeWidth="1.8" />
    <Wire d="M20 86 H46" hot />
    <Tip x={48} y={86} hot />
    <Box x={132} y={38} w={112} h={64} />
    {range(3).map((i) => (
      <path key={i} d={`M132 ${60 + i * 21} H244`} stroke={EDGE} strokeWidth="1" />
    ))}
    <path d="M188 38 V102" stroke={EDGE} strokeWidth="1" />
    <rect x={132} y={60} width={112} height={21} fill={HOT} opacity="0.18" />
    <Wire d="M84 86 H128" />
    <Tip x={130} y={86} />
    <Wire d="M244 70 H286 V34" hot />
    <Tip x={286} y={32} a={-90} hot />
    <Wire d="M244 92 H286 V138" />
    <Pin n={1} x={44} y={58} />
    <Pin n={2} x={156} y={120} />
    <Pin n={3} x={222} y={120} />
    <Pin n={4} x={306} y={34} />
  </>
))

/** Bits cannot travel on a voice line, so make them sing. */
figure('modem', 5, () => {
  const bits = [1, 0, 1]
  let d = 'M18 52'
  bits.forEach((b, i) => {
    const x = 18 + i * 22
    d += ` L${x} ${b ? 40 : 62} L${x + 22} ${b ? 40 : 62}`
  })
  return (
    <>
      <path d={d} fill="none" stroke={HOT} strokeWidth="1.8" />
      <Box x={94} y={54} w={48} h={44} />
      <Wire d="M84 76 H90" />
      <Wire d="M18 76 V52" />
      <Wire d="M62 52 H84 V76" />
      <Tip x={92} y={76} />
      <Wire d={sine(102, 76, 32, 3, 8)} hot />
      <Wire d={sine(146, 62, 48, 4, 6)} hot />
      <Wire d={sine(146, 90, 48, 2, 10)} hot />
      <path d="M170 108 V126 H206" stroke={EDGE} strokeWidth="1.2" fill="none" />
      <Box x={198} y={54} w={48} h={44} />
      <Wire d={sine(206, 76, 32, 3, 8)} hot />
      <Wire d="M246 76 H262 V52" hot />
      <path d={`M262 52 L262 40 L284 40 L284 62 L306 62 L306 40 L322 40`} fill="none" stroke={HOT} strokeWidth="1.8" />
      <Pin n={1} x={30} y={22} />
      <Pin n={2} x={118} y={118} />
      <Pin n={3} x={170} y={144} />
      <Pin n={4} x={222} y={118} />
      <Pin n={5} x={306} y={20} />
    </>
  )
})

// --- Era 7: packet networks ---------------------------------------------------

/** Cut the message up, send the pieces by whatever road is free, put it back. */
figure('packet-switching', 4, () => (
  <>
    <Box x={12} y={68} w={56} h={34} />
    <path d="M20 78 H60 M20 88 H50" stroke={EDGE} strokeWidth="1.6" />
    {range(3).map((i) => (
      <g key={i}>
        <rect x={94} y={44 + i * 34} width={30} height={22} rx="2.5" fill={FILL} stroke={HOT} strokeWidth="1.4" />
        <path d={`M98 ${52 + i * 34} h10`} stroke={PIN} strokeWidth="2" />
      </g>
    ))}
    <Wire d="M68 84 L90 56 M68 84 H90 M68 84 L90 112" hot />
    <g stroke={LINE} strokeWidth="1.2" fill="none">
      <path d="M124 54 Q170 20 216 54" />
      <path d="M124 84 H216" />
      <path d="M124 118 Q170 152 216 118" />
    </g>
    {[54, 84, 118].map((y, i) => (
      <circle key={i} cx={170} cy={y === 54 ? 30 : y === 118 ? 142 : 84} r="5" fill={FILL} stroke={EDGE} strokeWidth="1.4" />
    ))}
    {range(3).map((i) => (
      <rect key={i} x={216} y={44 + i * 34} width={30} height={22} rx="2.5" fill={FILL} stroke={HOT} strokeWidth="1.4" />
    ))}
    <Wire d="M246 56 L272 84 M246 84 H272 M246 112 L272 84" hot />
    <Box x={272} y={68} w={56} h={34} />
    <path d="M280 78 H320 M280 88 H310" stroke={EDGE} strokeWidth="1.6" />
    <Pin n={1} x={40} y={44} />
    <Pin n={2} x={109} y={18} />
    <Pin n={3} x={170} y={64} />
    <Pin n={4} x={300} y={44} />
  </>
))

/** Every packet carries where it is going and where it came from, or it is rubbish. */
figure('addressing', 4, () => (
  <>
    <rect x={40} y={40} width={260} height={90} rx="4" fill={FILL} stroke={LINE} strokeWidth="1.6" />
    <path d="M40 74 H300" stroke={EDGE} strokeWidth="1.2" />
    <path d="M124 40 V74 M212 40 V74" stroke={EDGE} strokeWidth="1.2" />
    <rect x={40} y={40} width={84} height={34} fill={HOT} opacity="0.2" />
    <g stroke={EDGE} strokeWidth="2">
      <path d="M56 58 H108" />
      <path d="M142 58 H194" />
      <path d="M228 58 H274" />
    </g>
    <g stroke={LINE} strokeWidth="1.6">
      <path d="M58 94 H282 M58 110 H240" />
    </g>
    <Pin n={1} x={82} y={22} />
    <Pin n={2} x={168} y={22} />
    <Pin n={3} x={252} y={22} />
    <Pin n={4} x={170} y={148} />
  </>
))

/** Send more than you need to, so a bit that arrives wrong can be caught and asked for again. */
figure('error-correction', 4, () => {
  const bits = [1, 0, 1, 1, 0, 0, 1]
  return (
    <>
      <g>
        {bits.map((b, i) => (
          <rect key={i} x={30 + i * 26} y={44} width={20} height={24} rx="2" fill={b ? HOT : FILL} opacity={b ? 0.75 : 1} stroke={EDGE} strokeWidth="1.2" />
        ))}
        <rect x={30 + 7 * 26} y={44} width={20} height={24} rx="2" fill="none" stroke={PIN} strokeWidth="1.8" strokeDasharray="3 2" />
      </g>
      <Wire d="M170 76 V96" />
      <Tip x={170} y={98} a={90} />
      <g>
        {bits.map((b, i) => {
          const flipped = i === 4
          return (
            <rect
              key={i}
              x={30 + i * 26}
              y={106}
              width={20}
              height={24}
              rx="2"
              fill={flipped ? 'var(--fig-no)' : b ? HOT : FILL}
              opacity={flipped ? 0.8 : b ? 0.75 : 1}
              stroke={flipped ? 'var(--fig-no)' : EDGE}
              strokeWidth="1.2"
            />
          )
        })}
        <rect x={30 + 7 * 26} y={106} width={20} height={24} rx="2" fill="none" stroke={PIN} strokeWidth="1.8" strokeDasharray="3 2" />
      </g>
      <Pin n={1} x={16} y={56} />
      <Pin n={2} x={225} y={22} />
      <Pin n={3} x={144} y={152} />
      <Pin n={4} x={296} y={118} />
    </>
  )
})

/** Stop making one part at a time: make ten thousand at once, on one piece of silicon. */
figure('integrated-circuit', 4, () => (
  <>
    <ellipse cx="76" cy="86" rx="52" ry="52" fill={FILL} stroke={LINE} strokeWidth="1.6" />
    <path d="M34 118 L52 138" stroke={EDGE} strokeWidth="1.4" />
    <g stroke={EDGE} strokeWidth="1">
      {range(7).map((i) => (
        <path key={`a${i}`} d={`M${34 + i * 14} 40 V132`} />
      ))}
      {range(7).map((i) => (
        <path key={`b${i}`} d={`M26 ${44 + i * 14} H126`} />
      ))}
    </g>
    <rect x={62} y={72} width={14} height={14} fill={HOT} opacity="0.8" />
    <Wire d="M132 86 H166" hot />
    <Tip x={168} y={86} hot />
    <g>
      <rect x={186} y={54} width={92} height={64} rx="4" fill={FILL} stroke={LINE} strokeWidth="1.8" />
      <g stroke={EDGE} strokeWidth="1.4">
        {range(5).map((i) => (
          <path key={`l${i}`} d={`M186 ${62 + i * 13} h-14`} />
        ))}
        {range(5).map((i) => (
          <path key={`r${i}`} d={`M278 ${62 + i * 13} h14`} />
        ))}
      </g>
      <g stroke={HOT} strokeWidth="1" opacity="0.85">
        <path d="M198 66 H240 V96 H262" />
        <path d="M198 84 H222 V110 H266" />
        <path d="M198 104 H214" />
      </g>
    </g>
    <Pin n={1} x={76} y={22} />
    <Pin n={2} x={110} y={150} />
    <Pin n={3} x={232} y={36} />
    <Pin n={4} x={306} y={130} />
  </>
))

/** The part that fails first, and the reason a rebuilt exchange still hums. */
figure('electrolytic-capacitor', 4, () => (
  <>
    <g>
      <path d="M56 44 H150 a12 12 0 0 1 0 84 H56 a12 12 0 0 1 0 -84 Z" fill={FILL} stroke={LINE} strokeWidth="1.6" />
      <path d="M56 44 a12 12 0 0 0 0 84" fill="none" stroke={EDGE} strokeWidth="1.4" />
      <path d="M120 44 V128" stroke={HOT} strokeWidth="2" opacity="0.6" />
      <path d="M30 62 H50 M30 110 H50" stroke={LINE} strokeWidth="2" />
    </g>
    <Wire d="M170 86 H196" />
    <Tip x={198} y={86} />
    <g>
      <path d="M226 48 V124" stroke={LINE} strokeWidth="3" />
      <path d="M246 48 V124" stroke={HOT} strokeWidth="3" />
      <path d="M236 48 V124" stroke={PIN} strokeWidth="1.4" strokeDasharray="4 3" />
      <path d="M226 86 H206 M246 86 H286" stroke={LINE} strokeWidth="1.6" />
      <g fill={HOT} opacity="0.75">
        {range(4).map((i) => (
          <circle key={i} cx={252} cy={58 + i * 18} r="2.4" />
        ))}
      </g>
      <g fill={LINE}>
        {range(4).map((i) => (
          <circle key={i} cx={220} cy={58 + i * 18} r="2.4" />
        ))}
      </g>
    </g>
    <Pin n={1} x={104} y={22} />
    <Pin n={2} x={236} y={26} />
    <Pin n={3} x={288} y={62} />
    <Pin n={4} x={104} y={148} />
  </>
))

// --- Era 8: internetworking ---------------------------------------------------

/** Nobody speaks at once and everybody says they heard: the whole idea, in four arrows. */
figure('protocol', 4, () => (
  <>
    <path d="M60 26 V150" stroke={EDGE} strokeWidth="1.4" />
    <path d="M280 26 V150" stroke={EDGE} strokeWidth="1.4" />
    <circle cx="60" cy="26" r="7" fill={FILL} stroke={LINE} strokeWidth="1.5" />
    <circle cx="280" cy="26" r="7" fill={FILL} stroke={LINE} strokeWidth="1.5" />
    <Wire d="M60 54 L272 66" hot />
    <Tip x={274} y={66} a={3} hot />
    <Wire d="M280 84 L68 96" />
    <Tip x={66} y={96} a={183} />
    <Wire d="M60 114 L272 126" hot />
    <Tip x={274} y={126} a={3} hot />
    <Pin n={1} x={128} y={44} />
    <Pin n={2} x={210} y={90} />
    <Pin n={3} x={128} y={144} />
    <Pin n={4} x={306} y={26} />
  </>
))

/** Two networks that agree on nothing, and one box that only has to agree on the envelope. */
figure('internetworking', 4, () => {
  const cluster = (cx: number, cy: number, hot: boolean) =>
    range(5).map((i) => {
      const a = (i / 5) * Math.PI * 2 - Math.PI / 2
      const x = cx + 34 * Math.cos(a)
      const y = cy + 30 * Math.sin(a)
      return (
        <g key={i}>
          <path d={`M${cx} ${cy} L${x} ${y}`} stroke={hot ? HOT : LINE} strokeWidth="1.2" />
          <circle cx={x} cy={y} r="4.5" fill={FILL} stroke={EDGE} strokeWidth="1.3" />
        </g>
      )
    })
  return (
    <>
      {cluster(62, 84, false)}
      <circle cx="62" cy="84" r="7" fill={FILL} stroke={LINE} strokeWidth="1.6" />
      {cluster(278, 84, true)}
      <circle cx="278" cy="84" r="7" fill={FILL} stroke={HOT} strokeWidth="1.6" />
      <rect x={148} y={66} width={44} height={36} rx="4" fill={FILL} stroke={PIN} strokeWidth="1.8" />
      <path d="M160 78 h20 v10 h-20 Z" fill="none" stroke={PIN} strokeWidth="1.3" />
      <Wire d="M96 84 H144" />
      <Tip x={146} y={84} />
      <Wire d="M192 84 H240" hot />
      <Tip x={242} y={84} hot />
      <Pin n={1} x={62} y={22} />
      <Pin n={2} x={170} y={126} />
      <Pin n={3} x={170} y={40} />
      <Pin n={4} x={278} y={22} />
    </>
  )
})

/** Draw it once, shine light through it, and the pattern is in the silicon. */
figure('photolithography', 5, () => (
  <>
    <path d="M46 16 h60 l-14 22 h-32 Z" fill={FILL} stroke={LINE} strokeWidth="1.4" />
    <g stroke={HOT} strokeWidth="1.4">
      {range(5).map((i) => (
        <path key={i} d={`M${62 + i * 8} 38 V56`} />
      ))}
    </g>
    <rect x={34} y={56} width={84} height={9} fill={FILL} stroke={LINE} strokeWidth="1.4" />
    <g fill={LINE}>
      <rect x={46} y={56} width={14} height={9} />
      <rect x={78} y={56} width={14} height={9} />
    </g>
    <rect x={34} y={86} width={84} height={12} fill={HOT} opacity="0.3" stroke={EDGE} strokeWidth="1.2" />
    <rect x={34} y={98} width={84} height={16} fill={FILL} stroke={LINE} strokeWidth="1.4" />
    <Wire d="M132 86 H166" />
    <Tip x={168} y={86} />
    <g>
      <path d="M182 86 h84 v12 h-84 Z" fill={FILL} stroke={LINE} strokeWidth="1.4" />
      <rect x={182} y={74} width={12} height={12} fill={HOT} opacity="0.3" />
      <rect x={214} y={74} width={12} height={12} fill={HOT} opacity="0.3" />
      <rect x={252} y={74} width={12} height={12} fill={HOT} opacity="0.3" />
    </g>
    <Wire d="M224 118 V136" />
    <Tip x={224} y={138} a={90} />
    <path d="M182 140 h84 v14 h-84 Z" fill={FILL} stroke={LINE} strokeWidth="1.4" />
    <g fill={HOT} opacity="0.75">
      <rect x={186} y={140} width={12} height={14} />
      <rect x={218} y={140} width={12} height={14} />
      <rect x={250} y={140} width={12} height={14} />
    </g>
    <Pin n={1} x={128} y={26} />
    <Pin n={2} x={128} y={60} />
    <Pin n={3} x={20} y={92} />
    <Pin n={4} x={288} y={80} />
    <Pin n={5} x={288} y={147} />
  </>
))

/** One bit at a time is slow and it is still a computer. */
figure('one-bit-machine', 4, () => (
  <>
    <Box x={22} y={54} w={64} h={60} />
    {range(4).map((i) => (
      <rect key={i} x={32} y={62 + i * 13} width={44} height={9} rx="1.5" fill={i === 1 ? HOT : 'none'} opacity={i === 1 ? 0.7 : 1} stroke={EDGE} strokeWidth="1.1" />
    ))}
    <Wire d="M86 84 H124" />
    <Tip x={126} y={84} />
    <path d="M132 54 L132 114 L176 96 L176 72 Z" fill={FILL} stroke={LINE} strokeWidth="1.6" />
    <Wire d="M176 84 H214" hot />
    <Tip x={216} y={84} hot />
    <rect x={218} y={72} width={26} height={24} rx="2" fill={FILL} stroke={HOT} strokeWidth="1.6" />
    <path d="M226 84 h10" stroke={HOT} strokeWidth="2" />
    <Wire d="M244 84 H286 V138 H54 V120" hot />
    <Tip x={54} y={118} a={-90} hot />
    <Pin n={1} x={54} y={34} />
    <Pin n={2} x={154} y={34} />
    <Pin n={3} x={231} y={50} />
    <Pin n={4} x={170} y={154} />
  </>
))

/** Give the rules away and nobody can take the network back. */
figure('open-standard', 4, () => (
  <>
    <g>
      <rect x={22} y={40} width={72} height={92} rx="3" fill={FILL} stroke={LINE} strokeWidth="1.6" />
      <g stroke={EDGE} strokeWidth="1.5">
        <path d="M34 58 H82 M34 72 H82 M34 86 H70 M34 100 H82 M34 114 H62" />
      </g>
    </g>
    <Wire d="M100 86 H134" hot />
    <Tip x={136} y={86} hot />
    {range(3).map((i) => (
      <g key={i}>
        <rect x={150 + i * 10} y={46 + i * 6} width={58} height={72} rx="3" fill={FILL} stroke={i === 2 ? HOT : EDGE} strokeWidth="1.4" />
      </g>
    ))}
    <Wire d="M226 86 H256" />
    <Tip x={258} y={86} />
    <g>
      <Body x={286} y={72} s={0.7} />
      <Body x={286} y={132} s={0.7} />
      <Body x={314} y={102} s={0.7} />
    </g>
    <Pin n={1} x={58} y={22} />
    <Pin n={2} x={184} y={26} />
    <Pin n={3} x={300} y={22} />
    <Pin n={4} x={140} y={148} />
  </>
))

// --- putting one on the page --------------------------------------------------

/**
 * A technology, shown: the photograph of the real thing, the diagram of how it
 * works, and the numbered words for the diagram's pins.
 *
 * The photograph goes first because it answers "what am I even looking at",
 * which is the question a diagram cannot answer, and the diagram answers "and
 * how does that do anything", which is the question a photograph cannot.
 */
export function TechFigure({
  id,
  steps,
  photo,
  compact,
  photoOnly,
}: {
  id: string
  steps?: string[]
  photo?: Photo
  compact?: boolean
  /**
   * The photograph on its own.
   *
   * The dialogue player uses this: mid-scene, a reader wants to know what the
   * thing looks like, and a schematic with numbered pins is a thing to study
   * rather than a thing to glance at. The diagram lives in the glossary, one
   * click away, where studying it is the point.
   */
  photoOnly?: boolean
}) {
  const fig = photoOnly ? undefined : figureFor(id)
  if (!fig && !photo) return null
  return (
    <figure className={`figure${compact ? ' figure--compact' : ''}${photoOnly ? ' figure--photo' : ''}`}>
      {photo && (
        <div className="figure__photo">
          <img src={photo.src} alt="" loading="lazy" />
          <p className="figure__credit">
            <a href={photo.page} target="_blank" rel="noreferrer noopener">
              {photo.credit}
            </a>
            <span>{photo.license}</span>
          </p>
        </div>
      )}
      {fig && (
        <div className="figure__plate">
          <svg viewBox={`0 0 ${W} ${H}`} className="figure__svg" role="img" aria-hidden>
            {fig.draw()}
          </svg>
        </div>
      )}
      {/* A sibling of the drawing rather than a child of it, so a caller with
          room to spare can stand the walk-through beside the diagram instead
          of under it. The dialogue plate does exactly that. */}
      {fig && steps && steps.length > 0 && (
        <ol className="figure__steps">
          {steps.map((step, i) => (
            <li key={i}>{step}</li>
          ))}
        </ol>
      )}
    </figure>
  )
}
