/**
 * A photograph of each technology, and who to credit for it.
 *
 * Generated by `npm run fetch:photos` — do not edit by hand. The images live
 * in `assets/tech/` and are imported rather than fetched, so the game draws
 * its glossary with no network, which is the entire premise of the game.
 *
 * Every entry here is under a free licence and the credit line is rendered
 * under the picture, which is the condition those licences are given on.
 */

import courier from '../assets/tech/courier.jpg'
import noticeBoard from '../assets/tech/notice-board.jpg'
import signalFire from '../assets/tech/signal-fire.jpg'
import semaphore from '../assets/tech/semaphore.jpg'
import lineOfSight from '../assets/tech/line-of-sight.png'
import amRadio from '../assets/tech/am-radio.jpg'
import transmitter from '../assets/tech/transmitter.png'
import antenna from '../assets/tech/antenna.jpg'
import generator from '../assets/tech/generator.jpg'
import battery from '../assets/tech/battery.jpg'
import propagation from '../assets/tech/propagation.jpg'
import telegraph from '../assets/tech/telegraph.jpg'
import telegraphKey from '../assets/tech/telegraph-key.jpg'
import morseCode from '../assets/tech/morse-code.png'
import electromagnet from '../assets/tech/electromagnet.jpg'
import relayStation from '../assets/tech/relay-station.jpg'
import telephone from '../assets/tech/telephone.jpg'
import switchboard from '../assets/tech/switchboard.jpg'
import exchange from '../assets/tech/exchange.jpg'
import strowger from '../assets/tech/strowger.jpg'
import standard from '../assets/tech/standard.jpg'
import vacuumTube from '../assets/tech/vacuum-tube.jpg'
import glassblowing from '../assets/tech/glassblowing.jpg'
import sulphuricAcid from '../assets/tech/sulphuric-acid.jpg'
import oscillator from '../assets/tech/oscillator.jpg'
import amplifier from '../assets/tech/amplifier.jpg'
import coreMemory from '../assets/tech/core-memory.jpg'
import punchedCard from '../assets/tech/punched-card.jpg'
import binary from '../assets/tech/binary.png'
import routingTable from '../assets/tech/routing-table.png'
import modem from '../assets/tech/modem.jpg'
import packetSwitching from '../assets/tech/packet-switching.jpg'
import addressing from '../assets/tech/addressing.jpg'
import errorCorrection from '../assets/tech/error-correction.jpg'
import integratedCircuit from '../assets/tech/integrated-circuit.jpg'
import electrolyticCapacitor from '../assets/tech/electrolytic-capacitor.jpg'
import protocol from '../assets/tech/protocol.jpg'
import internetworking from '../assets/tech/internetworking.jpg'
import photolithography from '../assets/tech/photolithography.jpg'
import oneBitMachine from '../assets/tech/one-bit-machine.jpg'
import openStandard from '../assets/tech/open-standard.png'

export interface Photo {
  src: string
  /** Who made it. Shown under the picture, linking to the file's page. */
  credit: string
  /** The licence it is shown under, in the short form Commons uses. */
  license: string
  page: string
}

export const PHOTOS: Record<string, Photo> = {
  courier: {
    src: courier,
    credit: 'pony express',
    license: 'Public domain',
    page: 'https://commons.wikimedia.org/wiki/File:Pony_Express%2760_West_bound_1860.jpg',
  },
  'notice-board': {
    src: noticeBoard,
    credit: 'Joseph Barillari',
    license: 'CC BY-SA 3.0',
    page: 'https://commons.wikimedia.org/wiki/File:Infinite-corridor-bboard.jpeg',
  },
  'signal-fire': {
    src: signalFire,
    credit: 'Radomianin',
    license: 'CC BY-SA 4.0',
    page: 'https://commons.wikimedia.org/wiki/File:Beacon_Stawa_M%C5%82yny,_%C5%9Awinouj%C5%9Bcie.jpg',
  },
  semaphore: {
    src: semaphore,
    credit: 'Lokilech at German Wikipedia',
    license: 'CC BY-SA 3.0',
    page: 'https://commons.wikimedia.org/wiki/File:OptischerTelegraf.jpg',
  },
  'line-of-sight': {
    src: lineOfSight,
    credit: 'Rudolfs Davis Strazds',
    license: 'CC BY-SA 4.0',
    page: 'https://commons.wikimedia.org/wiki/File:VHF_propagation.png',
  },
  'am-radio': {
    src: amRadio,
    credit: 'Amitbalani',
    license: 'CC0',
    page: 'https://commons.wikimedia.org/wiki/File:Antique_wooden_AM_radio_manufactured_in_Bharat.jpg',
  },
  transmitter: {
    src: transmitter,
    credit: 'LuckyLouie',
    license: 'CC BY-SA 3.0',
    page: 'https://commons.wikimedia.org/wiki/File:WDET-FM_transmitter.png',
  },
  antenna: {
    src: antenna,
    credit: 'Larry D. Moore',
    license: 'CC BY 4.0',
    page: 'https://commons.wikimedia.org/wiki/File:Ketchikan_radio_tower.jpg',
  },
  generator: {
    src: generator,
    credit: 'Audrius Meškauskas',
    license: 'CC BY-SA 3.0',
    page: 'https://commons.wikimedia.org/wiki/File:Military_engine_generator.jpg',
  },
  battery: {
    src: battery,
    credit: 'No machine-readable author provided. Shaddack assumed (based on copyright claims).',
    license: 'Public domain',
    page: 'https://commons.wikimedia.org/wiki/File:Photo-CarBattery.jpg',
  },
  propagation: {
    src: propagation,
    credit: 'Kf4yfd, Noldoaran, Augiasstallputzer~commonswiki',
    license: 'CC BY-SA 3.0',
    page: 'https://commons.wikimedia.org/wiki/File:Skywave.jpg',
  },
  telegraph: {
    src: telegraph,
    credit: 'John Schanlaub from Lafayette,IN, USA',
    license: 'CC BY 2.0',
    page: 'https://commons.wikimedia.org/wiki/File:Wallace_Study-Telegraph.jpg',
  },
  'telegraph-key': {
    src: telegraphKey,
    credit: 'Wikimedia Commons',
    license: 'Public domain',
    page: 'https://commons.wikimedia.org/wiki/File:J38TelegraphKey.jpg',
  },
  'morse-code': {
    src: morseCode,
    credit: 'Thirunavukkarasye-Raveendran',
    license: 'Public domain',
    page: 'https://commons.wikimedia.org/wiki/File:Dots_and_dashes_P_morse_code.svg',
  },
  electromagnet: {
    src: electromagnet,
    credit: 'MikeRun',
    license: 'CC BY-SA 4.0',
    page: 'https://commons.wikimedia.org/wiki/File:Electromagnet-with-9V-battery.jpg',
  },
  'relay-station': {
    src: relayStation,
    credit: 'Daderot',
    license: 'Public domain',
    page: 'https://commons.wikimedia.org/wiki/File:Telegraph_relay,_1850s.jpg',
  },
  telephone: {
    src: telephone,
    credit: 'Berthold Werner',
    license: 'CC BY-SA 3.0',
    page: 'https://commons.wikimedia.org/wiki/File:Telefon_BW_2012-02-18_13-44-32.JPG',
  },
  switchboard: {
    src: switchboard,
    credit: 'Joseph A. Carr',
    license: 'Attribution',
    page: 'https://commons.wikimedia.org/wiki/File:Jersey_Telecom_switchboard_and_operator.jpg',
  },
  exchange: {
    src: exchange,
    credit: 'Doyle of London',
    license: 'CC BY-SA 4.0',
    page: 'https://commons.wikimedia.org/wiki/File:Telephone_Exchange,_Hither_Green_(Southeast_View_-_01).jpg',
  },
  strowger: {
    src: strowger,
    credit: 'Brock Craft / Thatbrock at en.wikipedia',
    license: 'CC BY-SA 3.0',
    page: 'https://commons.wikimedia.org/wiki/File:Uniselector_Stepper_detail.jpg',
  },
  standard: {
    src: standard,
    credit: 'Andrewa at English Wikipedia',
    license: 'CC BY-SA 3.0',
    page: 'https://commons.wikimedia.org/wiki/File:Rjxx.jpg',
  },
  'vacuum-tube': {
    src: vacuumTube,
    credit: 'Wikimedia Commons',
    license: 'CC BY 2.0',
    page: 'https://commons.wikimedia.org/wiki/File:IBMVacuumTubeModule.jpg',
  },
  glassblowing: {
    src: glassblowing,
    credit: 'KamauxKamau',
    license: 'CC BY-SA 4.0',
    page: 'https://commons.wikimedia.org/wiki/File:Glass_bubble.jpg',
  },
  'sulphuric-acid': {
    src: sulphuricAcid,
    credit: 'W. Oelen',
    license: 'CC BY-SA 3.0',
    page: 'https://commons.wikimedia.org/wiki/File:Sulphuric_acid_96_percent_extra_pure.jpg',
  },
  oscillator: {
    src: oscillator,
    credit: 'Unknown authorUnknown author',
    license: 'Public domain',
    page: 'https://commons.wikimedia.org/wiki/File:Dynatron_signal_generator_1931.jpg',
  },
  amplifier: {
    src: amplifier,
    credit: 'W. W. Smith',
    license: 'Public domain',
    page: 'https://commons.wikimedia.org/wiki/File:Vacuum_tube_HF300_shortwave_RF_power_amplifier_from_1938.jpg',
  },
  'core-memory': {
    src: coreMemory,
    credit: 'Konstantin Lanzet',
    license: 'CC BY-SA 3.0',
    page: 'https://commons.wikimedia.org/wiki/File:KL_CoreMemory.jpg',
  },
  'punched-card': {
    src: punchedCard,
    credit: 'José Antonio González Nieto - cropped by Eyesinthefire',
    license: 'CC BY 4.0',
    page: 'https://commons.wikimedia.org/wiki/File:2punchCards-square.jpg',
  },
  binary: {
    src: binary,
    credit: 'Elaz85',
    license: 'CC BY-SA 4.0',
    page: 'https://commons.wikimedia.org/wiki/File:Binary_number_table.png',
  },
  'routing-table': {
    src: routingTable,
    credit: 'User:NAME',
    license: 'CC BY-SA 4.0',
    page: 'https://commons.wikimedia.org/wiki/File:Bgp_rtable.png',
  },
  modem: {
    src: modem,
    credit: 'secretlondon123',
    license: 'CC BY-SA 2.0',
    page: 'https://commons.wikimedia.org/wiki/File:Analogue_modem_-_acoustic_coupler.jpg',
  },
  'packet-switching': {
    src: packetSwitching,
    credit: 'Chris Richardson',
    license: 'CC BY-SA 2.0',
    page: 'https://commons.wikimedia.org/wiki/File:The_Steam_Packet_-_geograph.org.uk_-_1296000.jpg',
  },
  addressing: {
    src: addressing,
    credit: 'Achiri Bitamsimli',
    license: 'CC BY-SA 4.0',
    page: 'https://commons.wikimedia.org/wiki/File:IP_address_blocked.jpg',
  },
  'error-correction': {
    src: errorCorrection,
    credit: 'Image credit: Xiaoli Sun, NASA Goddard',
    license: 'Public domain',
    page: 'https://commons.wikimedia.org/wiki/File:Reed%E2%80%93Solomon_error_correction_Mona_Lisa_LroLrLasercomFig4.jpg',
  },
  'integrated-circuit': {
    src: integratedCircuit,
    credit: 'Raimond Spekking',
    license: 'CC BY-SA 4.0',
    page: 'https://commons.wikimedia.org/wiki/File:Extron_DMP_128_-_board_-_Microchip_24LC512-9701.jpg',
  },
  'electrolytic-capacitor': {
    src: electrolyticCapacitor,
    credit: 'Elcap',
    license: 'CC0',
    page: 'https://commons.wikimedia.org/wiki/File:Electrolytic_capacitors-P1090328.JPG',
  },
  protocol: {
    src: protocol,
    credit: 'Ardika6879',
    license: 'CC BY-SA 4.0',
    page: 'https://commons.wikimedia.org/wiki/File:TCPIP_Model.jpg',
  },
  internetworking: {
    src: internetworking,
    credit: 'Internetviet',
    license: 'CC BY-SA 4.0',
    page: 'https://commons.wikimedia.org/wiki/File:Logo-internetvietnam.net.jpg',
  },
  photolithography: {
    src: photolithography,
    credit: 'UCL Mathematical & Physical Sciences from London, UK',
    license: 'CC BY 2.0',
    page: 'https://commons.wikimedia.org/wiki/File:Cleanroom_-_photolithography_lab_(9150555748).jpg',
  },
  'one-bit-machine': {
    src: oneBitMachine,
    credit: 'Konstantin Lanzet (with permission)',
    license: 'CC BY-SA 3.0',
    page: 'https://commons.wikimedia.org/wiki/File:KL_Intel_P8051.jpg',
  },
  'open-standard': {
    src: openStandard,
    credit: 'University of Southern California',
    license: 'Public domain',
    page: 'https://commons.wikimedia.org/wiki/File:IPv4_RFC_791_first_page.png',
  },
}

export const photoFor = (id: string): Photo | undefined => PHOTOS[id]
