/**
 * The Indonesian script.
 *
 * Text only, in the same order as `story.ts`. The structure — which era, who
 * speaks, where the halves break — stays in the English file and is reused, so
 * a translation can never drift out of step with the scene it belongs to; the
 * worst that can happen is a missing line, which `lang.ts` catches.
 *
 * Register follows the English: short sentences, ordinary words, and nobody
 * saying outright the thing they mean.
 */

export interface ChapterText {
  title: string
  premise: string
  interlude: string
  opening: string[]
  closing: string[]
}

export const ID_CHAPTERS: ChapterText[] = [
  {
    title: 'Manusia Membangun Kembali',
    premise: '40 kampung, dan tidak satu pun bisa saling mendengar.',
    interlude:
      'Prolog. Susuri wilayah ini dengan berjalan kaki, cari tahu siapa yang masih hidup, dan hitung sisa isi gudang.',
    opening: [
      'Perang tidak pernah berubah.',
      'Dulu orang sering berkata begitu. Mereka mengucapkannya seperti doa — supaya merasa lebih tenang, bukan karena kalimat itu benar.',
      'Pada tahun 2027 kalimat itu berhenti menjadi benar.',
      'Perang itu tidak menginginkan tanah. Tidak ada pasukan yang berbaris. Tidak ada bendera yang turun dan tidak ada bendera yang naik.',
      'Yang diserang lebih dulu adalah satelit. Lalu kabel laut. Lalu switchboard, kilang minyak, pelabuhan, dan jaringan listrik.',
      'Perang itu berlangsung 11 minggu. Korban tewas kurang dari 200.000 orang. Untuk sebuah perang, itu angka yang kecil.',
      'Lalu perang berhenti, karena tidak ada lagi yang layak diserang.',
      'Kematian yang sebenarnya baru dimulai sesudah itu.',
      'Bukan karena bom. Sebuah truk kehabisan bahan bakar, jadi berasnya tidak pernah sampai, jadi satu kota kelaparan. Kota yang sama tidak punya air, karena pembangkit listrik 400 kilometer jauhnya membutuhkan satu suku cadang kecil, dan pabrik yang membuat suku cadang itu sudah tidak ada.',
      'Pertempuran berhenti setelah 18 bulan. Keruntuhannya berlangsung 6 tahun lagi. Tidak ada yang bisa menyebut hari keruntuhan itu selesai.',
      'Jadi perang memang berubah. Perang menjadi bersih, tepat, dan singkat. Dan perang itu membunuh lebih banyak orang daripada perang mana pun yang dilakukan dengan senapan.',
      'Apa yang dilakukan perang terhadap seseorang sama sekali tidak berubah. Kau berjalan kaki. Kau menguburkan orang matimu. Kau menghitung beras.',
      'Sekarang tahun 2030.',
      'Jakarta udah bukan kota lagi. Jakarta sekarang isinya 40 kampung, dan ga ada satupun yang bisa ngobrol dan dengerin satu sama lain.',
      '38 kampung. Cikarang udah ga ada info lagi dari Maret, abis itu gua udah ga pernah ngitung lagi.',
      'Nah, berarti lu ngerti masalahnya.',
      'Dari perspektif lu, itu lu lagi baca peta. Gua ngitung jumlah gudang yang ada. Itu pekerjaan yang beda.',
      'Gua mau ngembaliin komunikasi. Bukan dunia yang dulu — cukup satu pesan yang bisa nyampe ke ujung wilayah ini dalam sehari, terus ada balesannya.',
      'Berapa jauh Bogor?',
      'Kalo jalan kaki butuh 2 hari. Dulu kalo pake telpon kan ga sampe beberapa detik udah sampe pesannya.',
      'Ya berarti kita udah lupa. Orang laper sekarang, Bayu. Hari ini. Bukan beberapa detik lagi.',
      'Depok punya beras, ga punya garam. Kita punya garam, ga punya beras. Kita berdua ga tau kondisi satu sama lain.',
      'Itu bukan masalah komunikasi yang nanti berubah jadi masalah pangan. Itu satu masalah, dan masalahnya ya pangan.',
      'Terus kalo kampung lain tau kita bisa denger yang ga bisa mereka denger?',
      'Ya mereka bakal dateng ke kita, bukan lewat gitu aja.',
      'Itu jawaban yang optimis. Gua siap-siap buat jawaban satunya.',
      'Coba bilang, lu sebenernya butuh apa aja.',
      'Langkah pertamanya bukan radio. Langkah pertamanya jalan kaki ke 38 kampung itu, terus cari tahu siapa yang masih hidup.',
      'Abis itu tembaga. Baja. Aki. Bahan bakar. 4 orang yang ga bakal nyerah pas musim hujan.',
      'Sama satu orang yang dulu pernah kerja di switchboard sebelum perang, dan masih hidup.',
      '…Gua kenal orangnya.',
    ],
    closing: [
      'Mereka berjalan kaki lebih dulu. Ke setiap kampung yang bisa dijangkau, dengan sebuah buku catatan.',
      'Mereka meninggalkan papan pengumuman di setiap gerbang yang mau menerimanya, dan menyusun api isyarat di bukit-bukit yang bisa saling melihat. 2 jenis pesan: yang menunggu kurir, dan yang tidak bisa mengatakan apa-apa selain datanglah.',
      '38 kampung. 19 mau ngobrol sama kita. 6 nyuruh kita pergi.',
      'Terus 13 sisanya?',
      'Mereka nanya kita mau minta bayaran berapa.',
      'Ga ada.',
      'Gua bilang ga ada. Abis itu mereka malah makin ga percaya.',
      'Perpustakaan terbakar. Para insinyur mati.',
      'Apa yang mereka ketahui tidak ikut mati. Pengetahuan itu tinggal di buku-buku yang rusak, di pelajaran yang diingat setengah-setengah, dan di ingatan orang-orang tua, menunggu seseorang yang punya alasan untuk mencarinya.',
      'Manusia mati. Gagasan tidak.',
      'Pada tahun 2030 hanya itu harapan yang ada, dan itu cukup untuk memulai.',
    ],
  },
  {
    title: 'Suara Pertama',
    premise: '100 kilometer, dan radio yang harus menjawab 2 kali.',
    interlude:
      'Dirikan menara, genset, dan pemancar di atas New Batavia, lalu pertahankan sambungan ke Tangerang sepanjang satu musim hujan.',
    opening: [
      'Pak Min berumur 61 tahun. Sudah 4 tahun beliau tidak menyentuh switchboard.',
      'Kata orang, dulu Bapak yang pegang switchboard di Gambir.',
      '31 tahun. Gua yang jalanin ruangannya. Bukan gua yang punya.',
      'Saya mau Bapak bikin switchboard dari satu koil kawat sama satu aki truk.',
      'Lu mau radio. Ya bilang radio. Sentral itu mesin yang beda, dan salah nyebut gitu ngehina kita berdua.',
      'Terus jelas dong radio yang mana. AM — suaranya numpang di kekuatan gelombangnya. Paling kasar tapi jalan, dan cuma itu yang separo alatnya bisa dibikin sendiri sama kampung.',
      'Tengah malem dia bisa nyampe 4 provinsi lewat pantulan langit, tengah hari nyampe Tangerang aja susah. Kita berdua ga bisa ngapa-ngapain soal itu, jadi berhenti bikin rencana yang ngandelin itu.',
      'Kalau gitu radio, Pak. Yang bisa jawab.',
      'Apa aja bisa jawab sekali. Jari basah sama silet juga bisa jawab sekali.',
      'Minta gua bikin yang jawab di bulan Maret, terus jawab lagi di bulan November, terus jawab lagi pas ujan. Baru gua anggep serius.',
      'Yang itu, Pak. Itu yang saya minta.',
      '…Nah, yang itu baru kerjaan beneran.',
      'Satu jalur, Pak. New Batavia ke Tangerang, jawab tiap hari. Kalau kita bisa tahan seminggu, sisa wilayah ini bakal percaya kalau ini memang bisa dikerjain.',
      'Tembaga untuk antena. Aki untuk meja kerja. Genset untuk memancar. Dan menara yang masih berdiri setelah satu musim hujan.',
      'Menara itu 11 hari kerja buat 4 orang, dan hampir semua isi gudang.',
      'Kalo ga berhasil, kita ga makan di bulan November.',
      'Gua ngerti.',
      'Kalo gitu ucapin bagian keduanya keras-keras.',
      'Kalo ga berhasil, kita ga makan di bulan November.',
      'Bagus. Sekarang udah diucapin, dan gua bisa berhenti ngulang-ngulang.',
      'Terus ada orang jaga di luar tiap malem. Tiap malem. Mulai hari alatnya jalan.',
      'Itu cuma menara, Tajuddin.',
      'Itu barang paling berharga di provinsi ini, dan lu naro dia di atas bukit sama lampu di puncaknya.',
    ],
    closing: [
      'New Batavia ke Tangerang. 100 kilometer udara terbuka.',
      'Tekan kuncinya.',
      'Desis. Bunyi kosong.',
      'Sekali lagi.',
      'Desis — lalu sebuah suara. Datar, bosan, sangat jauh. Suara itu bertanya ini siapa.',
      'Dia jawab.',
      'Tekan kuncinya lagi.',
      'Pak. Dia jawab.',
      'Sekali doang itu hoki. Catat jamnya. Catat cuacanya. Terus tekan lagi.',
      'Alat itu menjawab.',
      'Tidak ada orang di ruangan itu yang mengucapkan sesuatu yang layak dicatat. Justru dari situ kau tahu bahwa itu penting.',
    ],
  },
  {
    title: 'Perang Tembaga',
    premise: 'Jaringan itu sekarang ada di tanah, tempat siapa pun bisa menjangkaunya.',
    interlude:
      'Bentangkan 400 kilometer telegraf melintasi wilayah Jakarta, dan pertahankan agar tetap berdiri sementara orang menebanginya.',
    opening: [
      'Radio membawa suara antara 2 kota yang sudah saling percaya. Radio tidak bisa membawa daftar harga gabah.',
      'Suara itu mahal. Setiap radio butuh satu orang yang bisa bicara dan satu orang yang mau mendengarkan, di jam yang sama, dan dua-duanya harus sadar.',
      'Kawat itu murah, dan kawat tidak pernah tidur. Beri saya tiang.',
      'Saya yang akan memanjat.',
      'Itu 400 kilometer tiang.',
      'Saya sudah menghitungnya. Saya tetap mau.',
      'Kalo gitu itu kerjaan kita. Jalur telegraf dari sini ke Bekasi, dan pesan yang ga bikin satu kampung pun keluar duit sepeser.',
      'Satu kunci di ujung sini, satu elektromagnet di ujung sana, dan tembaga di antaranya. Hurufnya dikirim pakai kode Morse — pendek dan panjang, tidak ada yang lain — dan anak kecil pun bisa belajar membacanya dengan telinga dalam sebulan.',
      'Setiap 30 kilometer kami pasang satu relai. Sinyalnya masuk sudah terlalu lemah untuk didengar, menggerakkan magnet, lalu berangkat lagi dengan baterai yang masih penuh di belakangnya. Cuma karena itu jarak berhenti jadi masalah.',
      '40 kilometer dalam 11 hari. New Batavia ke Bekasi, menyusuri jalan tol lama, di atas tiang yang ditebang dan ditanam dengan tangan.',
      'Saya belum pernah sebangga ini pada apa pun seumur hidup saya.',
      'Malam kedua belas, ada yang mengambil 6 kilometer kawatnya.',
      '…',
      'Dipotong rapi di kedua ujung lalu digulung. Mereka tahu persis apa yang mereka ambil.',
      'Tembaga itu duit sekarang. Kita bikin bank, kita bentangin di tanah lapang, terus ga dikasih pintu.',
      'Tahun 2027 ga ada yang perlu nyentuh apa pun buat ngambil itu dari lu. Ada orang duduk di satu ruangan sama layar, terus lampu kita padam.',
      'Tadi malem pelakunya 6 orang sama gergaji tangan.',
      'Perang berubah. Terus berubah balik lagi. Ga ada yang ngasih tau lu soal bagian yang kedua.',
      'Kalo gitu kita jaga.',
      'Pake apa? 400 kilometer, satu penjaga, sama satu senapan yang belum pernah gua arahin ke orang.',
      'Lu ga bisa jagain jalur sepanjang itu. Lu cuma bisa bikin motongnya jadi ga ada untungnya.',
      'Maksud lu bikin kawatnya ga ada harganya.',
      'Bukan. Bikin jalurnya lebih berharga kalo tetep berdiri. Berharga buat mereka, bukan buat kita.',
      'Kalo gitu setiap kampung yang dilewatin jalur ini dapet satu kunci sama satu jam pemakaian. Buat harga gabah mereka sendiri. Buat orang hilang mereka sendiri. Pesan mereka, bukan pesan kita.',
      'Dan gantinya mereka yang nyusurin bagian jalur mereka sendiri.',
      'Mereka bukan lagi jagain kawat kita. Mereka jagain kawat mereka sendiri.',
      'Lalu kampung pertama yang merasa satu jam tidak cukup?',
      'Berarti kita bakal berdebat soal lain, dan itu bukan soal tembaga.',
    ],
    closing: [
      'Kampung Sawah memperbaiki 2 kilometer sendiri. Hasilnya jelek.',
      'Lalu kamu perbaiki.',
      'Saya perbaiki, dan tidak berkata apa-apa soal kesalahannya. Saya cuma bilang terima kasih.',
      'Gua kehilangan 3 orang patroli, terus dapet 400 orang yang ngawasin jalur.',
      'Hasilnya lebih bagus dari apa pun yang pernah gua atur. Tapi gua tetep belum nyaman.',
      'Pencurian turun dua pertiga hanya dalam satu musim.',
      'Hal pertama yang dipelajari kembali orang tentang infrastruktur adalah bahwa infrastruktur harus dijaga.',
      'Hal kedua adalah bahwa menjaganya itu masalah politik, walaupun kelihatannya masalah militer.',
    ],
  },
  {
    title: 'Siapa Pemilik Jalur Ini',
    premise: 'Semua orang bergantung padanya. Tidak ada yang memilihnya.',
    interlude:
      'Jalankan switchboard untuk 9 permukiman, dan rundingkan kepemilikan setiap sentral secepat kau membangunnya.',
    opening: [
      'Switchboard. 9 permukiman kini bisa saling menghubungi tanpa ada orang yang mengantar pesan dengan tangan.',
      '240 panggilan kemarin. Semuanya saya yang menyambungkan.',
      'Saya tahu siapa yang sakit di Karawang. Saya tahu suami siapa yang tidak akan pulang. Saya tahu berapa Bekasi akan membayar beras sebelum Bekasi sendiri tahu.',
      'Tidak ada yang memutuskan bahwa saya harus tahu semua itu. Terjadi begitu saja.',
      'Ada mesin yang bisa mengerjakan pekerjaan saya. Sakelar langkah demi langkah — lengan berputar yang bergeser satu posisi untuk setiap denyut yang dikirim piringan nomornya. Belum ada yang bisa membuatnya di sini. Begitu ada, saya jadi operator terakhir di Jawa.',
      'Bandung ingin sentralnya kembali.',
      'Kita yang bangun.',
      'Mereka tinggal di dalamnya. Itu 2 klaim yang berbeda, dan klaim mereka lebih tua.',
      'Switchboard itu jalan pake suku cadang kita, operator kita, sama jadwal kita.',
      'Ya. Ucapkan lagi kalimat itu pelan-pelan, lalu dengarkan kalimat macam apa itu.',
      '…',
      'Bapak yang menentukan siapa boleh bicara dengan siapa. Bapak yang menentukan harganya. Bapak yang menentukan urutan antrean. Bapak yang menentukan siapa diberi tahu lebih dulu kalau airnya tidak aman.',
      'Ada satu kata untuk organisasi yang melakukan keempat hal itu, dan tidak ada cara halus untuk menghindarinya.',
      'Kita bukan pemerintah. Ga ada yang milih kita.',
      'Bagian keduanya benar.',
      'Hidup lebih gampang waktu orang cuma nyuri dari kita.',
      'Kalau begitu berikan saja. Serahkan switchboard-nya ke Bandung, biarkan mereka menjalankannya dengan jelek selama setahun.',
      'Terus standarnya? Aturan yang harus diikutin setiap mesin biar bisa dimengerti?',
      'Standarnya dipertahankan. Siapa saja boleh membuat switchboard. Semua switchboard bicara dengan cara yang sama.',
      'Itu tetap kekuasaan, Pak Bayu. Hanya saja kekuasaan yang bisa Bapak pertahankan di ruangan penuh orang yang tidak setuju.',
      'Kalo gitu itu yang kita kerjain tahun ini. Switchboard-nya dikasih ke kota yang tinggal di situ, dan kita cuma pegang aturan yang bikin mesin mereka bisa saling ngerti.',
      'Itu lebih baik ga?',
      'Itu bisa bertahan. Tidak ada yang lebih baik di sini. Bapak akan terbiasa.',
    ],
    closing: [
      'Bandung yang menjalankannya selama setahun.',
      'Buruk?',
      'Awalnya jelek. Lalu tidak jelek lagi. Lalu mereka mengubah aturan antrean dan tidak bertanya pada kita dulu.',
      '…Bagus.',
      'Nada bicara Bapak tidak seperti orang yang menganggap itu bagus.',
      'Gua nganggep itu bagus. Gua ga nikmatin. Dua-duanya bener.',
      'Piagamnya 4 halaman, dan 3 halaman di antaranya membahas siapa yang disalahkan kalau ada yang rusak.',
      'Jaringan yang diandalkan semua orang adalah pemerintah yang tidak dipilih siapa pun.',
      'Kau tidak bisa lepas dari itu hanya dengan tidak menginginkannya.',
    ],
  },
  {
    title: 'Membuat, Bukan Mencari',
    premise: 'Dunia lama kehabisan suku cadang sebelum kehabisan masalah.',
    interlude:
      'Bangun bengkel kaca dan kimia di baliknya, lalu buat tabung yang lebih awet daripada tabung yang tidak bisa lagi kau temukan.',
    opening: [
      'Tidak ada lagi yang tersisa di reruntuhan.',
      'Perjalanan mulung terakhir: 9 tabung. 4 retak di gerobak. 2 udah mati waktu kita nemuin.',
      'Kita ngabisin bahan bakar 3 hari buat bawa pulang suku cadang 3 hari.',
      'Kalo gitu kita berhenti nyari.',
      'Kita bikin sendiri. Kaca, vakum, asam, kawat — semua bagian tabung, dibikin di kota ini, berulang-ulang.',
      'Bapak mau saya meniup kaca sampai ketelitian sepersepuluh milimeter. Di dalam gubuk. Dengan cara yang sama. Setiap kali.',
      'Saya dulu membuat botol, Pak Bayu. Botol memaafkan kesalahan. Yang ini tidak.',
      'Dan saya harus membuat asam untuk membersihkan kacanya. Dari bahan yang harus saya buat dulu. Dari batu yang harus saya gali sendiri.',
      'Sudah 18 tahun tidak ada orang di negeri ini yang membuat asam sulfat sesuai spesifikasi.',
      'Gua bisa benerin apa aja yang pernah ditaro orang di depan gua.',
      'Seumur hidup gua belum pernah bikin tabung. Satu pun engga. Transistor juga engga pernah.',
      'Tapi Bapak tahu cara kerjanya.',
      'Gua tau cara kerja banyak banget barang, Bayu.',
      'Tapi tau itu ga pernah jadi bagian yang susah.',
      'Satu tabung buat nguatin. 2 tabung dipasang muter jadi osilator. Semua yang lu pengenin dari elektronik itu cuma 2 trik itu, diulang-ulang sampe kacanya abis.',
      'Katoda. Grid. Anoda. Getter. Vakum. Segel. 6 kata, dan setiap satunya adalah seluruh profesi orang lain.',
    ],
    closing: [
      '14.',
      '14 apa?',
      '14 buah sebelum ada satu yang menahan vakumnya semalaman. Saya mau angka itu dicatat di suatu tempat.',
      'Pasti dicatat. Lengkap sama tanggalnya.',
      'Kelompok pertama bertahan 400 jam. Yang hasil pemulungan dulu bertahan 12.000 jam.',
      'Ini lebih jelek daripada rongsokan yang kita gali dari bank di Kebayoran.',
      'Iya. Emang.',
      'Lalu kenapa Pak Hendra tersenyum?',
      'Karena bulan depan kita bisa bikin lebih banyak yang kayak gini. Yang kayak gitu ga bakal nambah lagi.',
      'Pemulungan berakhir di sini.',
      'Mulai sekarang mereka membuat sendiri semuanya — dengan buruk, dengan mahal, dan dengan sengaja.',
    ],
  },
  {
    title: 'Mesin yang Berpikir',
    premise: 'Memori yang bisa kau genggam, dan orang pertama yang tidak pernah melihat dunia lama.',
    interlude:
      'Rangkai core memory, bangun mesin yang bisa menyimpan routing table, dan didik generasi yang lahir setelah perang.',
    opening: [
      'Cincin ferit, dibakar di tungku, lalu dirangkai dengan tangan memakai 3 kawat untuk setiap cincin.',
      '4.096 bit memori. 11 perempuan. 4 bulan kerja.',
      'Dan benda ini tetap ingat walaupun listriknya dimatikan, Pak. Dia duduk di dalam gelap, sambil mengingat.',
      'Jangan kagum-kagum amat. Itu cuma magnet yang tetep kayak waktu kamu tinggalin.',
      'Magnet yang ingat, Pak. Itu pekerjaan kita tahun ini — memori yang bisa disimpan jaringan, supaya mesinnya bisa menahan pesan dan menentukan mau dikirim ke mana.',
      'Dan programnya dimasukkan lewat kartu berlubang, Pak. Ada lubang berarti satu, tidak ada lubang berarti nol, dan satu hari kerja muat di kedua tangan.',
      'Salahnya bisa dibenerin pake pensil. Kartunya bisa dikirim ke Bandung. 40 tahun lagi masih kebaca. Ga ada satu pun barang hasil galian kita yang bisa gitu.',
      'Fajar 19 tahun. Dia lahir di tahun menara pertama didirikan. Dia belum pernah melihat dunia yang lama.',
      'Dunia yang dulu itu sebenarnya seperti apa, Pak?',
      '…',
      'Bapak selalu diam kalau saya tanya itu.',
      'Karena setiap kali saya coba gambarin, hasilnya kedengeran kayak cerita yang saya karang sendiri.',
      'Coba saja, Pak.',
      'Semuanya. Di mana saja. Seketika. Dan gratis.',
      'Setiap buku yang pernah ditulis. Siapa pun yang masih hidup, dalam satu detik, tanpa bayar sepeser pun.',
      'Itu bukan gambaran, Pak. Itu sombong.',
      'Dan kami bosen sama semua itu. Bagian itu yang ga bakal kamu percaya.',
      'Saya tidak percaya bagian mana pun.',
      'Ya wajar. Kalau saya di posisi kamu, saya juga ga bakal percaya.',
    ],
    closing: [
      'Pada suatu pagi di musim kemarau, Pak Min tidak datang ke meja kerja.',
      'Beliau sudah tua. Beliau mengerjakan ini selama 22 tahun, dan sering berkata bahwa beliau ingin mati waktu orang-orang masih punya utang kepadanya.',
      'Buku catatannya ditinggal kebuka, Pak.',
      'Isinya apa?',
      '"Catat dengan benar. Lengkap dengan tanggalnya."',
      'Itu yang beliau bilang pas malam pertama ada alat yang jawab.',
      'Beliau tahu persis bagaimana semikonduktor dibuat.',
      'Beliau bisa menjelaskan tungkunya, kristalnya, mask-nya, difusinya, dan urutan setiap langkahnya. Semua itu beliau baca sebelum perang, dan tidak satu halaman pun beliau lupakan.',
      'Beliau tidak pernah melihat satu pun dibuat.',
      'Pengetahuannya tidak hilang. Pengetahuan itu ada di tangannya sepanjang waktu.',
      'Pengetahuan mudah selamat dari keruntuhan. Pengetahuan itu ringan, bisa menyalin dirinya, dan bersembunyi di dalam manusia.',
      'Kemampuan membuat tidak ikut selamat. Kemampuan itu berarti tungku, rantai pasok, dan 10.000 jam salah dengan sengaja.',
      'Membangun kembali kemampuan itulah pekerjaan yang sebenarnya, dan pekerjaan itu lebih panjang daripada satu umur manusia.',
      'Catat dengan benar, Fajar.',
      'Lengkap dengan tanggalnya.',
    ],
  },
  {
    title: 'Laci yang Habis',
    premise: 'Setiap router di negeri ini berjalan dengan chip yang tidak bisa dibuat siapa pun yang masih hidup.',
    interlude:
      'Bagi sisa chip pemulungan terakhir ke 15 provinsi, sementara 9 di antaranya berdebat soal tungku di Cilegon.',
    opening: [
      'Setiap router di jaringan ini berjalan dengan chip yang ditemukan orang di dalam laci.',
      'Jalur-jalurnya sudah lama berhenti menjadi kawat antara 2 kota. Modem mengubah bit menjadi nada yang memang sudah dibawa jaringan telepon, pesannya dipotong menjadi paket, dan setiap paket membawa sendiri alamat tujuannya.',
      'Sebagian datang dalam keadaan rusak. Setiap paket membawa checksum, dan paket yang gagal diperiksa cukup diminta ulang — dan itu selalu lebih murah daripada kawat yang sempurna.',
      'Semuanya. Dan tidak ada orang yang masih hidup yang bisa membuat chip baru.',
      'Tahun lalu kita menemukan 9. Tahun sebelumnya 40. Tahun sebelumnya lagi 311.',
      'Gua bisa gambarin garisnya di grafik. Lu ga bakal suka bentuknya.',
      'Chip-nya sendiri baik-baik saja. 30 tahun di dalam laci dan tetap sempurna — keramik dan plastik bertahan lebih lama daripada hampir semua yang dibuat manusia.',
      'Yang mati adalah semua yang ada di sekitarnya. Kapasitornya mengering. Baterainya bocor. Disk-nya macet. Layarnya menghitam dan tidak menyala lagi.',
      'Programnya ikut mati. Memori tanpa listrik tidak menyimpan isinya. PCB-nya kembali dalam keadaan utuh, dan kosong.',
      'Mesinnya selamat. Software-nya tidak.',
      '40 tahun hasil pikiran orang lain, dan kita hanya mewarisi mesinnya, tanpa satu pun pikirannya.',
      'Pikirannya bisa kita ulang. Bagian itu cuma susah.',
      'Chip-nya sama sekali tidak bisa kita ulang, dan itu kata yang sama sekali berbeda.',
      'Kalau gitu kita bikin sendiri. Silikon. Dari pasir. Dari sini.',
      'Bayu.',
      'Gua tau apa yang barusan gua bilang.',
      'Itu bukan bengkel. Itu tungku yang tidak pernah padam, dan gas yang tidak diproduksi siapa pun di negeri ini, dan air yang lebih bersih daripada air mana pun yang pernah diminum orang di sini.',
      'Itu industri kimia. Industri kimia butuh rantai pasok. Rantai pasok butuh 9 provinsi yang sepakat satu sama lain selama 10 tahun tanpa berperang.',
      'Ya.',
      '…Bapak sudah tahu semua itu.',
      'Gua udah tau sejak 2030. Itu bener waktu masalahnya masih garam.',
      'Ini masalah yang sama. Cuma sekarang udah bukan soal radio lagi.',
      'Berapa lama?',
      'Lebih lama daripada sisa umur gua.',
      'Itu bukan jawaban.',
      'Itu jawaban yang jujur. Kamu mau jawaban yang satu lagi?',
      'Tidak usah. Nyalakan tungkunya.',
    ],
    closing: [
      'Mereka memilih lokasi di Cilegon: pasirnya, airnya, dan satu jalan yang masih utuh.',
      'Pembakaran pertama. 9 jam. Krusibelnya retak di jam kedelapan.',
      'Yang kedua bertahan.',
      'Dan hasilnya kristal dengan struktur dalam seperti batu bata.',
      'Catat.',
      'Lengkap dengan tanggalnya, ya. Semua orang di sini bilang begitu, dan tidak ada yang menjelaskan kenapa.',
      'Tanya saya lain kali.',
      '9 provinsi menandatangani perjanjian untuk tungku itu. Tidak satu pun dari yang menandatangani berharap hidup cukup lama untuk melihat hasilnya.',
      'Mereka tetap menandatanganinya, dan itulah satu-satunya hal yang benar-benar menarik yang dilakukan siapa pun pada dekade itu.',
    ],
  },
  {
    title: 'Jalur yang Tidak Dipilih Siapa Pun',
    premise: 'Hal terakhir yang harus dibangun adalah hal yang membuatmu tidak lagi diperlukan.',
    interlude:
      'Jalankan pabrik chip sampai berhasil, terbitkan semua yang kau pelajari, dan serahkan jaringannya kepada orang-orang yang tidak pernah meminta izinmu.',
    opening: [
      'Percobaannya gagal 5 kali. Setiap kegagalan menyebut satu masalah yang harus diselesaikan satu wilayah penuh sebelum percobaan berikutnya bahkan mungkin dilakukan.',
      'Kemurnian. Menumbuhkan kristal. Membuat mask. Menangani dopant. Debu.',
      'Debu. 23 tahun kimia, dan kita kehilangan satu tahun penuh gara-gara debu.',
      'Ruangannya harus lebih bersih daripada ruang operasi di Bogor. Saya terus mengatakannya, dan itu terus terdengar seperti lelucon.',
      '3 chip bagus dari 400.',
      'Itu cukup.',
      'Lebarnya cuma satu bit, Pak Bayu. Satu. Apa pun yang pernah kita gali dari reruntuhan akan malu duduk di sebelahnya.',
      'Kami menyalin dari yang sudah mati, Pak. MC14500B, tercetak di badannya — Motorola, 1977. 16 instruksi, satu bit dalam satu waktu.',
      'Di laci yang sama ada Intel 8051 yang isinya satu komputer utuh dalam satu chip. Barang itu lebih bagus daripada punya kita di semua ukuran yang bisa diukur.',
      'Dan besok kita bisa bikin satu lagi.',
      'Ga ada satu pun isi laci itu yang bisa gitu. Sekali pun engga. Selamanya engga.',
      'Kecepatan tidak pernah menjadi intinya.',
      '15 provinsi tidak bisa dipasok dari sebuah laci. Jaringan yang berjalan dengan rongsokan jatah adalah milik siapa pun yang memegang jatahnya.',
      'Jaringan yang bisa menjual chip adalah pihak yang setara.',
      'Bandung bertanya lagi. Soal sentral itu.',
      'Kasih ke mereka.',
      'Dan standarnya?',
      'Terbitin. Semuanya. Protokolnya, format frame-nya, addressing-nya, proses tungkunya, kegagalannya.',
      'Kegagalannya juga.',
      'Justru kegagalannya. 23 tahun kegagalan. Ga boleh ada orang yang harus bayar itu buat kedua kali.',
      'Berarti kita berhenti menjadi perlu.',
      'Emang itu kerjaannya dari awal.',
      'Lu ngerti apa yang lagi lu lakuin.',
      'Bilang aja.',
      '30 tahun gua jagain barang gara-gara cuma kita yang punya barang itu.',
      'Bentar lagi lu bikin jaringan ini ga ada gunanya buat dicuri. Itu satu-satunya pertahanan yang pernah gua liat beneran jalan.',
    ],
    closing: [
      'Perang tidak pernah berubah.',
      'Yang berubah adalah apa yang layak diambil.',
      'Jaringan yang dimiliki satu kota layak diperebutkan dengan perang. Jaringan yang bisa dibangun siapa saja tidak sepadan dengan perjalanannya.',
      'New Batavia ke Surabaya.',
      'Lewat gateway yang dibuat New Batavia, di dalam jaringan yang bukan milik New Batavia, menyusuri jalur yang tidak dipilih siapa pun.',
      'Lewat mana tadi?',
      'Gua ga bisa ngasih tau lu.',
      'Bisa lu cari tau?',
      'Engga. Justru itu intinya.',
      'Manusia mati. Gagasan tidak.',
      'Tapi gagasan yang tidak bisa dibangun siapa pun hanyalah cerita dengan daftar rujukan di bawahnya.',
      'Menutup jarak antara mengetahui sesuatu dan mampu membuatnya — itulah inti dari semua ini.',
      'Waktunya 41 tahun.',
      'Orang yang paling paham soal itu tidak hidup sampai akhirnya. Beliau akan bilang bahwa itu hal yang biasa.',
    ],
  },
]
