import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
p.on('pageerror', (e) => errors.push(String(e)))
p.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
await p.goto('http://localhost:5219/', { waitUntil: 'networkidle' })
await p.getByRole('button', { name: /Era 0 . The Survey/ }).click()
await p.getByRole('button', { name: 'Begin', exact: true }).click()
await p.waitForSelector('.relay__map')
await p.waitForTimeout(1500)
console.log('era0 early:', (await p.locator('.relay__caption').innerText()).replace(/\n/g, ' | '))
await p.locator('.relay__skip').click()
await p.waitForSelector('.relay__verdict')
console.log('era0 verdict:', (await p.locator('.relay__verdict').innerText()).replace(/\n/g, ' | '))
await p.screenshot({ path: 'tools/render/relay-era0.png' })
// Indonesian, to prove the translation reaches the card.
await b.close()
const b2 = await chromium.launch()
const q = await b2.newPage({ viewport: { width: 1440, height: 900 } })
await q.goto('http://localhost:5219/', { waitUntil: 'networkidle' })
await q.getByRole('button', { name: 'ID', exact: true }).click()
await q.getByRole('button', { name: /Era 0 . Penjajakan/ }).click()
await q.getByRole('button', { name: /Mulai/ }).first().click()
await q.waitForSelector('.relay__map')
await q.waitForTimeout(1200)
console.log('id caption:', (await q.locator('.relay__caption').innerText()).replace(/\n/g, ' | '))
await q.locator('.relay__skip').click()
await q.waitForSelector('.relay__verdict')
console.log('id verdict:', (await q.locator('.relay__verdict').innerText()).replace(/\n/g, ' | '))
console.log('errors:', errors)
await b2.close()
